/* Tama Andrea Studio — shared frontend controller */
const CONFIG=Object.freeze({
  wa:'6281274852534',
  apps:'https://script.google.com/macros/s/AKfycbwLjqCqyOFnss7B0L_I23mnahnPCzcY1hX3Tqj_LiQ-ghHGhM3n-QYJTNMJmOyeM01MlQ/exec',
  consult:'https://konsultasidesignbytamaandrea.vercel.app/',
  portfolio:'https://muhammadandreatama.vercel.app/',
  review:'https://g.page/r/Cem_1B9sdErlEBM/review'
});
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const ICONS={sun:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42"/></svg>',moon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 14.5A8.5 8.5 0 0 1 9.5 3.5 8.5 8.5 0 1 0 20.5 14.5Z"/></svg>',menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18"/></svg>'};
function theme(){const root=document.documentElement,saved=localStorage.getItem('ta-theme');if(saved==='light'||saved==='dark')root.dataset.theme=saved;const b=$('#theme');if(!b)return;const paint=()=>{const light=root.dataset.theme!=='dark';b.innerHTML=light?ICONS.sun:ICONS.moon;b.setAttribute('aria-label',light?'Gunakan tema gelap':'Gunakan tema terang')};paint();b.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';localStorage.setItem('ta-theme',root.dataset.theme);paint()})}
function nav(){const btn=$('#menu'),panel=$('#mobileMenu');const items=[['Desain','/layanan.html'],['Servis IT','/servis.html'],['Karya','/karya.html'],['Tentang','/tentang.html'],['Info','/info.html'],['Bantuan','/bantuan.html'],['Konsultasi',CONFIG.consult,true],['Pesan','/pesan.html',false,true]];const current=location.pathname.split('/').pop()||'index.html';const mark=(href,external)=>!external&&href.endsWith(current);const render=root=>{if(!root)return;root.innerHTML=items.map(([label,href,external,primary])=>`<a${primary?' class="btn btn-primary"':''} href="${href}"${external?' target="_blank" rel="noopener noreferrer"':''}${mark(href,external)?' aria-current="page"':''}>${label}</a>`).join('')};render($('.nav-links'));render(panel);if(!btn||!panel)return;const set=open=>{panel.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);btn.setAttribute('aria-expanded',String(open));btn.setAttribute('aria-label',open?'Tutup menu':'Buka menu');btn.innerHTML=open?ICONS.close:ICONS.menu};set(false);btn.addEventListener('click',()=>set(!panel.classList.contains('open')));panel.addEventListener('click',e=>{if(e.target.closest('a'))set(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape')set(false)});window.addEventListener('resize',()=>{if(innerWidth>980)set(false)})}
function reveal(){const els=$$('.reveal');if(!els.length)return;if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});els.forEach(e=>io.observe(e))}
function wa(){const base=`https://wa.me/${CONFIG.wa}`;$$('[data-wa]').forEach(b=>b.addEventListener('click',()=>{const text=b.dataset.wa||'Halo Tama Andrea Studio, saya ingin menghubungi Anda.';window.open(`${base}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}))}
function lightbox(){const box=$('#lightbox'),img=$('#lightboxImage');if(!box||!img)return;const close=()=>{box.classList.remove('open');box.hidden=true;img.removeAttribute('src')};$$('[data-lightbox]').forEach(el=>el.addEventListener('click',()=>{img.src=el.dataset.lightbox;img.alt=el.alt||'Preview karya';box.hidden=false;box.classList.add('open')}));$('#lightboxClose')?.addEventListener('click',close);box.addEventListener('click',e=>{if(e.target===box)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
function assets(){const map={'/logo-tamaandreastudio.jpg':'/assets/images/brand/logo-tamaandreastudio.jpg','/partner-logo1.png':'/assets/images/partners/partner-logo1.png','/figma-logo.png':'/assets/images/tools/figma-logo.png','/illustrator-logo.png':'/assets/images/tools/illustrator-logo.png','/photoshop-logo.png':'/assets/images/tools/photoshop-logo.png','/Canva.jpg':'/assets/images/payments/Canva.jpg','/Gopay.jpg':'/assets/images/payments/Gopay.jpg','/Iblispaint.jpg':'/assets/images/payments/Iblispaint.jpg','/Money.jpg':'/assets/images/payments/Money.jpg','/dana.jpg':'/assets/images/payments/dana.jpg'};for(let i=1;i<=7;i++)map[`/Karya${i}.png`]=`/assets/images/portfolio/Karya${i}.png`;$$('img').forEach(img=>{const src=img.getAttribute('src');if(src&&map[src])img.src=map[src]})}
function parseApiError(data,fallback){const err=new Error(data?.message||fallback||'Server tidak dapat memproses permintaan.');err.code=data?.code||'UNKNOWN_ERROR';err.retryAfter=Number(data?.retryAfterSeconds||data?.retryAfter||0);return err}
async function apiGet(params){const qs=new URLSearchParams(params);const r=await fetch(`${CONFIG.apps}?${qs.toString()}`,{headers:{Accept:'application/json'}});let data={};try{data=await r.json()}catch(_){throw new Error('Respons database tidak valid.')}if(!r.ok||data.status==='error')throw parseApiError(data,'Server tidak dapat memproses permintaan.');return data}
async function apiPost(body){const r=await fetch(CONFIG.apps,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8',Accept:'application/json'},body:JSON.stringify(body)});let data={};try{data=await r.json()}catch(_){throw new Error('Respons database tidak valid.')}if(!r.ok||data.status==='error')throw parseApiError(data,'Server tidak dapat memproses permintaan.');return data}
function stats(){if(!$('#stats'))return;apiGet({action:'stats'}).then(raw=>{const d=raw.data||raw;if($('#statKarya'))$('#statKarya').textContent=d.totalPesanan??'0';if($('#statKlien'))$('#statKlien').textContent=d.selesai??'0'}).catch(()=>{})}
function captcha(){const q=$('#captchaQ'),input=$('#captcha');if(!q||!input)return()=>true;const a=Math.floor(Math.random()*7)+2,b=Math.floor(Math.random()*7)+1;q.textContent=`${a} + ${b}`;input.dataset.answer=String(a+b);return()=>input.value.trim()===input.dataset.answer}
function formDataObject(form){const data={};for(const [key,value] of new FormData(form).entries()){if(key==='address'||key==='_gotcha')continue;if(Object.prototype.hasOwnProperty.call(data,key))data[key]=`${data[key]}, ${value}`;else data[key]=value}return data}

/* Conservative input quality / privacy / abuse heuristics. Never stores field values. */
const INPUT_SECURITY={minHumanSeconds:3,maxRepeatedSubmit:4,cooldownSeconds:60};
const SENSITIVE_PATTERNS=[/\bpassword\b/i,/\bpasscode\b/i,/\bkata sandi\b/i,/\botp\b/i,/\brecovery\s*code\b/i,/\bverification\s*code\b/i,/\bkode\s*(verifikasi|otp|pemulihan)\b/i,/\bapi[_ -]?key\b/i,/\bsecret\s*key\b/i,/\baccess[_ -]?token\b/i,/BEGIN\s+(RSA|OPENSSH|EC|DSA|PRIVATE)\s+KEY/i];
function inputSignals(value){const text=String(value||'').trim(),signals=[];if(SENSITIVE_PATTERNS.some(re=>re.test(text)))signals.push('sensitive');if(/(.)\1{7,}/.test(text))signals.push('repeat-chars');if(text.length>40&&!/[aeiou]/i.test(text))signals.push('low-readable');if(/[!?.,]{6,}/.test(text)||/([!?])\1{3,}/.test(text))signals.push('punctuation');return{text,signals}}
function humanInputCheck(form){if(!form)return{ok:true};const started=Number(form.dataset.startedAt||Date.now()),elapsed=(Date.now()-started)/1000;const honeypots=$$('input[name="address"],input[name="_gotcha"],input[data-honeypot="true"]',form).filter(x=>String(x.value||'').trim());if(honeypots.length)return{ok:false,code:'BOT_SUSPECTED',message:'Permintaan tidak dapat diproses. Silakan coba lagi secara normal.'};if(elapsed<INPUT_SECURITY.minHumanSeconds)return{ok:false,code:'TOO_FAST',message:'Formulir dikirim terlalu cepat. Periksa kembali isian sebelum mencoba lagi.'};const webdriver=navigator.webdriver===true;const samples=$$('input:not([type="hidden"]),textarea,select',form).map(x=>x.value).join(' '),check=inputSignals(samples);if(webdriver)return{ok:false,code:'AUTOMATION_SUSPECTED',message:'Permintaan otomatis tidak dapat diproses.'};if(check.signals.includes('sensitive'))return{ok:false,code:'SENSITIVE_INPUT',message:'Jangan masukkan password, OTP, recovery code, token, atau private key ke dalam formulir.'};return{ok:true,signals:check.signals}}
function typoNotice(form){if(!form)return;$$('textarea,input[type="text"]',form).forEach(el=>el.addEventListener('blur',()=>{const text=String(el.value||'').trim();if(text.length<12)return;const s=inputSignals(text).signals.filter(x=>['repeat-chars','low-readable','punctuation'].includes(x));if(s.length){el.setCustomValidity('Teks tampaknya perlu diperiksa kembali agar lebih jelas.');el.dataset.inputWarning='1'}else{el.setCustomValidity('');delete el.dataset.inputWarning}}))}
function cooldownRemaining(key){const until=Number(sessionStorage.getItem(`ta-cooldown:${key}`)||0);return Math.max(0,Math.ceil((until-Date.now())/1000))}
function setCooldown(key,seconds){sessionStorage.setItem(`ta-cooldown:${key}`,String(Date.now()+Math.max(1,seconds)*1000))}
function runCooldownUI(element,key,seconds,message){if(!element)return;setCooldown(key,seconds);let remaining=Math.ceil(seconds);element.textContent=`${message||'Coba lagi nanti.'} Tunggu ${remaining} detik.`;const timer=setInterval(()=>{remaining--;if(remaining<=0){clearInterval(timer);sessionStorage.removeItem(`ta-cooldown:${key}`);element.textContent='Silakan coba lagi sekarang.'}else element.textContent=`${message||'Coba lagi nanti.'} Tunggu ${remaining} detik.`},1000)}
function failureGuard(key,element){const n=Number(sessionStorage.getItem(`ta-fails:${key}`)||0)+1;sessionStorage.setItem(`ta-fails:${key}`,String(n));if(n>=INPUT_SECURITY.maxRepeatedSubmit){sessionStorage.setItem(`ta-fails:${key}`,'0');runCooldownUI(element,key,INPUT_SECURITY.cooldownSeconds,'Terlalu banyak percobaan yang gagal.');return true}return false}
function clearFailureGuard(key){sessionStorage.removeItem(`ta-fails:${key}`);sessionStorage.removeItem(`ta-cooldown:${key}`)}

function orderForm(){const form=$('#orderForm');if(!form)return;form.dataset.startedAt=String(Date.now());typoNotice(form);let validCaptcha=captcha();const category=$('#service'),checks=$$('.order-check-section input[type="checkbox"]',form),android=checks.find(x=>/Android - Coming Soon/i.test(x.value));if(android)android.disabled=true;const sync=()=>{const cat=category?.value||'',design=cat==='Desain & Kreatif',it=cat==='Servis IT';$$('.order-check-section',form).forEach((section,i)=>{section.hidden=(i===0&&!design)||(i===1&&!it)});checks.forEach(x=>{if(x===android)return;if(x.closest('.order-check-section')?.hidden)x.checked=false})};category?.addEventListener('change',sync);sync();form.addEventListener('reset',()=>setTimeout(()=>{form.dataset.startedAt=String(Date.now());validCaptcha=captcha();sync()},0));form.addEventListener('submit',async e=>{e.preventDefault();const status=$('#formStatus'),btn=$('#submitBtn');status.textContent='';const cooldown=cooldownRemaining('order');if(cooldown){runCooldownUI(status,'order',cooldown,'Terlalu banyak percobaan.');return}const human=humanInputCheck(form);if(!human.ok){status.textContent=human.message;failureGuard('order',status);return}if(!validCaptcha()){status.textContent='Jawaban verifikasi belum benar.';failureGuard('order',status);validCaptcha=captcha();return}if(!form.reportValidity())return;const selected=$$('input[name="Layanan Dipilih"]:checked',form);if(!selected.length){status.textContent='Pilih minimal satu layanan yang dibutuhkan.';return}btn.disabled=true;status.textContent='Mengirim pesanan…';const data=formDataObject(form);data.clientRequestId=globalThis.crypto?.randomUUID?crypto.randomUUID():`web-${Date.now()}-${Math.random().toString(16).slice(2)}`;try{const out=await apiPost({action:'newOrder',data,clientRequestId:data.clientRequestId});const id=out.orderId||out.id;if(id){clearFailureGuard('order');status.textContent=`Pesanan berhasil. Kode order: ${id}`;showSuccess(id);form.reset()}else status.textContent='Pesanan diterima, tetapi kode order belum tersedia.'}catch(err){status.textContent=err.message||'Database tidak dapat dihubungi. Silakan coba lagi.';if(err.retryAfter)runCooldownUI(status,'order',err.retryAfter,'Server meminta jeda.');else failureGuard('order',status)}finally{btn.disabled=false}})}
function showSuccess(id){const modal=$('#success');if(!modal)return;$('#successId').textContent=id;modal.hidden=false;const copy=$('#successCopy');if(copy&&!copy.dataset.bound){copy.dataset.bound='1';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#successId').textContent)}catch(_){}})}$('#successClose')?.addEventListener('click',()=>modal.hidden=true,{once:true})}
function normalizeOrderId(value){const raw=String(value||'').trim().toUpperCase().replace(/^ORD[-\s]?/,'');return raw?`ORD-${raw.padStart(4,'0')}`:''}
function normalizeName(value){return String(value||'').trim().replace(/\s+/g,' ')}
function normalizeEmail(value){return String(value||'').trim().toLowerCase()}
function tracker(){const form=$('#trackerForm');if(!form)return;form.dataset.startedAt=String(Date.now());const result=$('#trackResult'),verify=$('#verifyPanel'),full=$('#verifiedResult');let currentOrderId='';form.addEventListener('submit',async e=>{e.preventDefault();const id=normalizeOrderId($('#trackInput').value);if(!/^ORD-\d{4,8}$/.test(id)){result.textContent='Masukkan nomor order yang valid.';return}currentOrderId=id;result.textContent='Mencari pesanan…';if(verify)verify.hidden=true;if(full)full.textContent='';try{const d=await apiGet({action:'track',id});const o=d.order;if(!o){result.textContent='Pesanan tidak ditemukan.';return}currentOrderId=normalizeOrderId(o.id);result.innerHTML=`<div class="result-grid"><div class="result-item"><small>ID Pesanan</small><b>${escapeHtml(o.id)}</b></div><div class="result-item"><small>Nama</small><b>${escapeHtml(o.nama||'—')}</b></div><div class="result-item"><small>Layanan</small><b>${escapeHtml(o.layanan||'—')}</b></div><div class="result-item"><small>Status</small><b>${escapeHtml(o.status||'—')}</b></div></div><p class="muted" style="margin-top:12px">Nama lengkap, email, detail, dan nota hanya dibuka setelah verifikasi nama + email.</p>`;if(verify)verify.hidden=false}catch(err){result.textContent=err.message||'Tidak dapat terhubung ke database saat ini.'}});verify?.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();if(!currentOrderId){full.textContent='Cari nomor order terlebih dahulu.';return}const cooldown=cooldownRemaining('verify');if(cooldown){runCooldownUI(full,'verify',cooldown,'Terlalu banyak percobaan.');return}const name=normalizeName($('#verifyName').value),email=normalizeEmail($('#verifyEmail').value);if(!name||!email){full.textContent='Nama dan email wajib diisi.';failureGuard('verify',full);return}const input=inputSignals(`${name} ${email}`);if(input.signals.includes('sensitive')){full.textContent='Jangan masukkan password, OTP, token, atau kode pemulihan.';failureGuard('verify',full);return}full.textContent='Memverifikasi…';try{const d=await apiPost({action:'verifyOrder',id:currentOrderId,name,email});const order=d.order||d.data?.order;if(!order){full.textContent='Verifikasi gagal.';failureGuard('verify',full);return}clearFailureGuard('verify');renderVerifiedOrder(order)}catch(err){full.textContent=err.message||'Verifikasi tidak dapat diproses.';if(err.retryAfter)runCooldownUI(full,'verify',err.retryAfter,'Server meminta jeda.');else failureGuard('verify',full)}})}
function renderVerifiedOrder(o){const box=$('#verifiedResult');if(!box)return;box.innerHTML=`<div class="verified-card"><div class="result-grid"><div class="result-item"><small>Nama lengkap</small><b>${escapeHtml(o.nama||'—')}</b></div><div class="result-item"><small>Email</small><b>${escapeHtml(o.email||'—')}</b></div><div class="result-item"><small>Layanan</small><b>${escapeHtml(o.layanan||'—')}</b></div><div class="result-item"><small>Status</small><b>${escapeHtml(o.status||'—')}</b></div><div class="result-item"><small>Estimasi</small><b>${money(o.estimasi)}</b></div><div class="result-item"><small>Pembayaran</small><b>${escapeHtml(o.payment||'—')}</b></div></div><div class="actions" style="margin-top:14px"><button class="btn btn-primary" type="button" id="invoicePrint">Cetak / Simpan PDF</button><button class="btn btn-secondary" type="button" id="invoiceImage">Unduh nota gambar</button></div></div>`;$('#invoicePrint').onclick=()=>printInvoice(o);$('#invoiceImage').onclick=()=>downloadInvoiceSvg(o)}
function money(v){const n=Number(String(v??'').replace(/[^\d.-]/g,''));return n?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n):'Belum ditetapkan'}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function xml(v){return escapeHtml(v)}
function invoiceHtml(o){return`<!doctype html><html lang="id"><head><meta charset="utf-8"><title>Nota ${escapeHtml(o.id)}</title><style>body{font-family:Arial,sans-serif;padding:40px;color:#111}h1{margin-bottom:4px}table{width:100%;border-collapse:collapse;margin-top:30px}td{padding:12px;border-bottom:1px solid #ddd}.total{font-size:22px;font-weight:700;margin-top:25px}</style></head><body><h1>Tama Andrea Studio</h1><div>Nota / Ringkasan Pesanan</div><table><tr><td>No. Order</td><td>${escapeHtml(o.id)}</td></tr><tr><td>Tanggal</td><td>${escapeHtml(o.tanggal||'—')}</td></tr><tr><td>Pelanggan</td><td>${escapeHtml(o.nama||'—')}</td></tr><tr><td>Email</td><td>${escapeHtml(o.email||'—')}</td></tr><tr><td>Layanan</td><td>${escapeHtml(o.layanan||'—')}</td></tr><tr><td>Status</td><td>${escapeHtml(o.status||'—')}</td></tr><tr><td>Pembayaran</td><td>${escapeHtml(o.payment||'—')}</td></tr></table><div class="total">Total/Estimasi: ${money(o.estimasi)}</div><p>Dokumen dibuat setelah verifikasi kepemilikan pesanan.</p></body></html>`}
function printInvoice(o){const w=window.open('','_blank','noopener');if(!w)return;w.document.write(invoiceHtml(o));w.document.close();w.focus();setTimeout(()=>w.print(),200)}
function downloadInvoiceSvg(o){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="700"><rect width="100%" height="100%" fill="#fff"/><text x="60" y="70" font-size="30" font-family="Arial" font-weight="700">TAMA ANDREA STUDIO</text><text x="60" y="115" font-size="22" font-family="Arial">NOTA / RINGKASAN PESANAN</text><text x="60" y="175" font-size="20" font-family="Arial">No. ${xml(o.id)}</text><text x="60" y="215" font-size="20" font-family="Arial">Tanggal: ${xml(o.tanggal||'—')}</text><text x="60" y="255" font-size="20" font-family="Arial">Pelanggan: ${xml(o.nama||'—')}</text><text x="60" y="295" font-size="20" font-family="Arial">Email: ${xml(o.email||'—')}</text><text x="60" y="335" font-size="20" font-family="Arial">Layanan: ${xml(o.layanan||'—')}</text><text x="60" y="375" font-size="20" font-family="Arial">Status: ${xml(o.status||'—')}</text><text x="60" y="415" font-size="20" font-family="Arial">Pembayaran: ${xml(o.payment||'—')}</text><text x="60" y="485" font-size="26" font-family="Arial" font-weight="700">Estimasi: ${xml(money(o.estimasi))}</text><text x="60" y="545" font-size="15" font-family="Arial">Dokumen dibuat setelah verifikasi kepemilikan pesanan.</text></svg>`;const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nota-${String(o.id||'order').replace(/[^A-Za-z0-9-]/g,'')}.svg`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function year(){$$('#year').forEach(e=>e.textContent=new Date().getFullYear())}
function boot(){assets();theme();nav();reveal();wa();lightbox();stats();orderForm();tracker();year()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
