/**
 * Tama Andrea Studio — Backend Core
 * V5.5 — Sheets API core. Admin security and technician extensions live in admin-security.gs.
 * Never put admin secrets in this file or in GitHub.
 */

const APP=Object.freeze({
  VERSION:'5.5.0',TIMEZONE:'Asia/Jakarta',CURRENCY:'IDR',ORDER_PREFIX:'ORD-',ORDER_WIDTH:4,
  MAX_BODY_BYTES:30000,PAGE_SIZE:20,MAX_PAGE_SIZE:50,VERIFY_SECONDS:900,
  PUBLIC_LIMIT:12,PUBLIC_WINDOW:600,VERIFY_LIMIT:5,VERIFY_WINDOW:600,
  STATUS:['Pending','Proses','Review','Selesai','Dibatalkan'],
  PAYMENT:['Belum Bayar','DP','Lunas','Dibatalkan'],
  PRIORITY:['Rendah','Normal','Menengah','Tinggi'],
  OS:['Windows 11 Home','Windows 11 Pro','Windows 11 Enterprise LTSC 2024','Ubuntu','Debian','Kali Linux'],
  METHOD:['Teknisi datang ke lokasi — Sabtu/Minggu','Saya membawa perangkat — bisa diantar setelah konfirmasi, termasuk malam hari']
});

const SHEETS=Object.freeze({ORDERS:'Orders',CUSTOMERS:'Customers',AUDIT:'Audit_Log',ERRORS:'Error_Log',REQUESTS:'Request_Index',SETTINGS:'Settings',SERVICE_NOTES:'Service_Notes',BOOT_KEYS:'Boot_Keys'});
const ORDER_HEADERS=['ID Pesanan','Tanggal Masuk','Tanggal Update','Nama Lengkap','Alamat Email','Kontak/WA','Kategori Layanan','Layanan Dipilih','Pilihan OS','Metode Layanan','Rincian Brief','Tenggat Waktu','Status','Estimasi Biaya','Status Pembayaran','Jumlah Revisi','Link Hasil','Prioritas Deadline','Hari Tersisa','Sumber','Client Request ID','Catatan Internal'];
const CUSTOMER_HEADERS=['Customer ID','Pertama Masuk','Terakhir Masuk','Nama','Email','Kontak/WA','Jumlah Pesanan','Order Terakhir','Status Customer','Catatan'];
const AUDIT_HEADERS=['Timestamp','Request ID','Actor','Action','Entity ID','Result','Detail'];
const ERROR_HEADERS=['Timestamp','Request ID','Action','Code','Message','Stack'];
const REQUEST_HEADERS=['Client Request ID','Order ID','Created At','Request Hash'];
const SETTINGS_HEADERS=['Key','Value','Description','Updated At'];

const SERVICE_CATALOG=Object.freeze({
  'Poster & Flyer Digital':{base:15000,min:15000,max:80000,group:'design'},
  'Banner Marketplace':{base:20000,min:20000,max:80000,group:'design'},
  'Konten Media Sosial':{base:20000,min:20000,max:85000,group:'design'},
  'Logo Profesional':{base:20000,min:20000,max:90000,group:'design'},
  'Desain Presentasi':{base:20000,min:20000,max:85000,group:'design'},
  'Edit Foto Produk':{base:20000,min:20000,max:80000,group:'design'},
  'Paket OS Basic - Rp90.000':{base:90000,min:90000,max:90000,group:'it'},
  'Paket OS + Office - Rp125.000':{base:125000,min:125000,max:125000,group:'it'},
  'Paket OS + Backup - Rp135.000':{base:135000,min:135000,max:135000,group:'it'},
  'Paket OS + Office + Backup - Rp160.000':{base:160000,min:160000,max:160000,group:'it'},
  'Diagnosis PC / laptop - Rp35.000':{base:35000,min:35000,max:35000,group:'it-diagnosis'},
  'Cek kesehatan SSD/HDD - Rp35.000':{base:35000,min:35000,max:35000,group:'it-add-on'},
  'Backup data sebelum instal ulang - mulai Rp40.000':{base:40000,min:40000,max:100000,group:'it-add-on'},
  'Driver & update dasar - mulai Rp25.000':{base:25000,min:25000,max:40000,group:'it-add-on'},
  'Cek kompatibilitas komponen & rekomendasi upgrade':{base:25000,min:25000,max:75000,group:'it-upgrade'},
  'Pasang / Upgrade RAM - Rp50.000':{base:50000,min:50000,max:50000,group:'it-install'},
  'Pasang SSD / HDD - Rp50.000':{base:50000,min:50000,max:50000,group:'it-install'},
  'Pasang CPU - Rp60.000':{base:60000,min:60000,max:60000,group:'it-install'},
  'Pasang GPU - Rp60.000':{base:60000,min:60000,max:60000,group:'it-install'},
  'Pasang PSU - Rp60.000':{base:60000,min:60000,max:60000,group:'it-install'},
  'Pasang / Upgrade 2 Komponen - Rp90.000':{base:90000,min:90000,max:90000,group:'it-install'},
  'Instal Microsoft Office - Rp35.000':{base:35000,min:35000,max:35000,group:'it-software'},
  'Restore / Flash iPhone - mulai Rp60.000':{base:60000,min:60000,max:100000,group:'it-device'},
  'Bantuan Find Hub Android - mulai Rp35.000':{base:35000,min:35000,max:75000,group:'it-device'},
  'Bantuan Find My / Lacak iPhone - mulai Rp35.000':{base:35000,min:35000,max:75000,group:'it-device'}
});

function onOpen(){SpreadsheetApp.getUi().createMenu('TA Backend').addItem('Setup / Periksa','setupBackend').addItem('Konfigurasi Admin','configureAdminSecurity').addItem('Health Check','runHealthCheck').addItem('Atur Spreadsheet ID','setSpreadsheetId').addToUi();}
function doGet(e){const rid=makeRequestId_();try{const a=getParam_(e,'action');if(a==='ping')return json_({status:'ok',service:'tama-andrea-studio-backend',version:APP.VERSION,requestId:rid,time:nowIso_()});if(a==='stats')return json_({status:'ok',requestId:rid,data:getPublicStats_(),updatedAt:formatDateTime_(new Date())});if(a==='track'){if(String(getParam_(e,'id')).length>80)throw appError_('VALIDATION_ERROR','Parameter terlalu panjang.');enforceRate_('public-track',APP.PUBLIC_LIMIT,APP.PUBLIC_WINDOW);const id=normalizeOrderId_(getParam_(e,'id'));if(!id)return errorResponse_('VALIDATION_ERROR','ID pesanan tidak valid.',rid);const o=findOrderById_(id);return o?json_({status:'ok',requestId:rid,order:publicOrder_(o)}):errorResponse_('NOT_FOUND','Pesanan tidak ditemukan.',rid);}if(a==='admin')return renderAdmin_();return json_({status:'ok',service:'Tama Andrea Studio',version:APP.VERSION,requestId:rid});}catch(err){logError_(rid,'GET',err.code||'INTERNAL_ERROR',err);return errorResponse_(err.code||'INTERNAL_ERROR',err.message||'Server mengalami kendala.',rid);}}
function doPost(e){const rid=makeRequestId_();let action='unknown';try{const raw=readBody_(e);action=String(raw.action||'').trim();if(!action)return errorResponse_('VALIDATION_ERROR','Action tidak ditemukan.',rid);if(action==='newOrder'){const d=raw.data||raw,crid=normalizeClientRequestId_(raw.clientRequestId||d.clientRequestId||'');enforceRate_('public-order',APP.PUBLIC_LIMIT,APP.PUBLIC_WINDOW);return json_(createNewOrderRecord_(d,{requestId:rid,clientRequestId:crid,source:'website'}));}if(action==='verifyOrder'){const id=raw.id||raw.orderId||'',name=raw.name||'',email=raw.email||'';enforceRate_('verify:'+hashShort_(id),APP.VERIFY_LIMIT,APP.VERIFY_WINDOW);return json_(verifyOrder_(id,name,email,rid));}if(action==='getVerifiedOrder')return json_(getVerifiedOrder_(raw.id||raw.orderId||'',raw.verificationToken||'',rid));return errorResponse_('UNKNOWN_ACTION','Action tidak dikenali.',rid);}catch(err){logError_(rid,action,err.code||'INTERNAL_ERROR',err);return errorResponse_(err.code||'INTERNAL_ERROR',err.message||'Permintaan tidak dapat diproses.',rid);}}
function setupBackend(){const ss=getSpreadsheet_();[[SHEETS.ORDERS,ORDER_HEADERS],[SHEETS.CUSTOMERS,CUSTOMER_HEADERS],[SHEETS.AUDIT,AUDIT_HEADERS],[SHEETS.ERRORS,ERROR_HEADERS],[SHEETS.REQUESTS,REQUEST_HEADERS],[SHEETS.SETTINGS,SETTINGS_HEADERS],[SHEETS.SERVICE_NOTES,['Note ID','Kategori','Judul','Ringkasan','Langkah Kerja','Peringatan / Batasan','Updated At']],[SHEETS.BOOT_KEYS,['Brand','Jenis Perangkat','Model / Motherboard','BIOS / UEFI','Boot Menu','Catatan','Updated At']]].forEach(function(d){configureSheet_(getOrCreateSheet_(ss,d[0],d[1]),d[1]);});const p=PropertiesService.getScriptProperties(),orders=ss.getSheetByName(SHEETS.ORDERS);if(!p.getProperty('TA_ORDER_SEQ'))p.setProperty('TA_ORDER_SEQ',String(findMaxOrderNumber_(orders)));const st=ss.getSheetByName(SHEETS.SETTINGS);writeSetting_(st,'BACKEND_VERSION',APP.VERSION,'Versi backend aktif.');writeSetting_(st,'TIMEZONE',APP.TIMEZONE,'Zona waktu operasional.');writeSetting_(st,'PUBLIC_TRACKING','MASKED_UNTIL_VERIFIED','Nama dan email disensor sampai verifikasi.');writeSetting_(st,'ADMIN_AUTH','3_LAYER','Gerbang → kode akses → identitas/password.');writeSetting_(st,'HOME_VISIT','SATURDAY_SUNDAY','Home visit hanya Sabtu/Minggu.');SpreadsheetApp.flush();return{status:'success',version:APP.VERSION,orderSequence:Number(p.getProperty('TA_ORDER_SEQ')||0)};}
function getOrCreateSheet_(ss,n,h){let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);ensureHeaders_(s,h);return s;}function configureSheet_(s,h){ensureHeaders_(s,h);s.setFrozenRows(1);try{s.getRange(1,1,1,h.length).setFontWeight('bold');}catch(_){}}function ensureHeaders_(s,h){if(s.getLastRow()===0){s.getRange(1,1,1,h.length).setValues([h]);return;}const ex=s.getRange(1,1,1,Math.max(h.length,s.getLastColumn())).getDisplayValues()[0];for(let i=0;i<h.length;i++)if(normalizeSearch_(ex[i])!==normalizeSearch_(h[i]))s.getRange(1,i+1).setValue(h[i]);}
function getDashboardData(searchTerm,token){requireAdmin_(token);const s=getOrdersSheet_(),q=normalizeSearch_(searchTerm),rows=q?searchOrders_(s,q):recentOrders_(s,APP.PAGE_SIZE);return{status:'ok',version:APP.VERSION,stats:dashboardStats_(s),orders:rows,sheetName:s.getName()};}
function updateOrderFromConsole(id,patch,token){requireAdmin_(token);const f=findOrderRow_(id);if(!f)throw appError_('NOT_FOUND','Pesanan tidak ditemukan.');const p=patch||{},r=f.values.slice();if(hasOwn_(p,'status'))r[12]=validateEnum_(p.status,APP.STATUS,'Status');if(hasOwn_(p,'statusPembayaran'))r[14]=validateEnum_(p.statusPembayaran,APP.PAYMENT,'Status pembayaran');if(hasOwn_(p,'jumlahRevisi'))r[15]=clampInt_(p.jumlahRevisi,0,99,'Jumlah revisi');if(hasOwn_(p,'prioritas'))r[17]=validateEnum_(p.prioritas,APP.PRIORITY,'Prioritas');if(hasOwn_(p,'link'))r[16]=safeCell_(String(p.link||'').slice(0,500));if(hasOwn_(p,'catatan'))r[21]=safeCell_(String(p.catatan||'').slice(0,1500));if(hasOwn_(p,'tenggat'))r[11]=parseDateInput_(p.tenggat,'Tenggat');r[2]=new Date();r[18]=computeDaysLeft_(r[11]);f.sheet.getRange(f.row,1,1,ORDER_HEADERS.length).setValues([r]);writeAudit_(makeRequestId_(),'admin','UPDATE_ORDER',f.id,'SUCCESS','Order diperbarui.');return{status:'ok',order:rowToOrder_(r,f.row)};}
function deleteOrderFromConsole(id,token){requireAdmin_(token);const f=findOrderRow_(id);if(!f)throw appError_('NOT_FOUND','Pesanan tidak ditemukan.');f.sheet.deleteRow(f.row);writeAudit_(makeRequestId_(),'admin','DELETE_ORDER',f.id,'SUCCESS','Order dihapus.');return{status:'ok',id:f.id};}
function saveOrderFromConsole(data,token){requireAdmin_(token);return createNewOrderRecord_(data||{},{requestId:makeRequestId_(),clientRequestId:'admin-'+makeToken_(),source:'admin'});}
function analyzeBriefFromConsole(service,brief,token){requireAdmin_(token);return analyzeOrder_(service,brief,'');}
function createNewOrderRecord_(params,meta){const req=meta.requestId||makeRequestId_(),input=normalizeOrderInput_(params||{});validatePayloadSize_(input);if(meta.clientRequestId)input.clientRequestId=normalizeClientRequestId_(meta.clientRequestId);if(input.clientRequestId){const old=findRequest_(input.clientRequestId);if(old){const ex=findOrderById_(old);return{status:'ok',duplicate:true,id:old,orderId:old,requestId:req,estimate:ex?ex.estimasi:0};}}const analysis=analyzeOrder_(input.layanan,input.brief,input.os),lock=LockService.getScriptLock();lock.waitLock(10000);try{const s=getOrdersSheet_(),id=nextOrderId_(s),now=new Date(),due=addBusinessDays_(now,analysis.days),r=new Array(ORDER_HEADERS.length).fill('');r[0]=id;r[1]=now;r[2]=now;r[3]=safeCell_(input.nama);r[4]=safeCell_(input.email);r[5]=safeCell_(input.wa);r[6]=safeCell_(input.kategori);r[7]=safeCell_(input.layanan);r[8]=safeCell_(input.os);r[9]=safeCell_(input.metode);r[10]=safeCell_(input.brief);r[11]=due;r[12]='Pending';r[13]=analysis.estimate;r[14]='Belum Bayar';r[15]=0;r[17]=analysis.priority;r[18]=analysis.days;r[19]=safeCell_(meta.source||'website');r[20]=safeCell_(input.clientRequestId);r[21]=safeCell_('Analyzer: '+analysis.summary+' | Risiko: '+(analysis.risks.join(', ')||'none'));const rn=s.getLastRow()+1;s.getRange(rn,1,1,ORDER_HEADERS.length).setValues([r]);s.getRange(rn,2,1,2).setNumberFormat('dd/MM/yyyy HH:mm');s.getRange(rn,12).setNumberFormat('dd/MM/yyyy');s.getRange(rn,14).setNumberFormat('#,##0');upsertCustomer_(input,id,now);if(input.clientRequestId)saveRequest_(input.clientRequestId,id,req);writeAudit_(req,meta.source==='admin'?'admin':'public','CREATE_ORDER',id,'SUCCESS','Order dibuat.');return{status:'ok',id:id,orderId:id,requestId:req,layanan:input.layanan,estimate:'Rp '+formatRupiah_(analysis.estimate),estimatePrice:analysis.estimate,estimateMin:analysis.min,estimateMax:analysis.max,deadline:formatDate_(due),priority:analysis.priority,days:analysis.days,analysis:{quality:analysis.quality,riskFlags:analysis.risks}};}finally{lock.releaseLock();}}
function normalizeOrderInput_(p){const nama=sanitizePlain_(p.Nama||p['Nama Lengkap']||p.nama,80),email=normalizeEmail_(p.Email||p['Alamat Email']),wa=String(p.WA||p.WhatsApp||p['Kontak/WA']||'').replace(/[^\d+]/g,''),kategori=sanitizePlain_(p.Kategori||p['Kategori Layanan']||p['Jenis Desain'],50),layanan=sanitizePlain_(p.Layanan||p['Layanan Dipilih']||p.service,800),os=sanitizePlain_(p.OS||p['Pilihan OS'],60),metode=sanitizePlain_(p.Metode||p['Metode Layanan'],150),brief=sanitizePlain_(p.Brief||p['Rincian Brief']||p['Keterangan Proyek'],5000);if(nama.length<2)throw appError_('VALIDATION_ERROR','Nama minimal 2 karakter.');if(!/^\S+@\S+\.\S+$/.test(email))throw appError_('VALIDATION_ERROR','Format email tidak valid.');if(wa&&!/^\+?\d{8,15}$/.test(wa))throw appError_('VALIDATION_ERROR','Nomor WhatsApp tidak valid.');if(layanan.length<2)throw appError_('VALIDATION_ERROR','Layanan belum dipilih.');if(brief.length<5)throw appError_('VALIDATION_ERROR','Keterangan kebutuhan terlalu singkat.');if(os&&APP.OS.indexOf(os)<0)throw appError_('VALIDATION_ERROR','Pilihan OS tidak dikenali.');if(metode&&APP.METHOD.indexOf(metode)<0)throw appError_('VALIDATION_ERROR','Metode layanan tidak dikenali.');const c=normalizeSearch_(kategori),l=normalizeSearch_(layanan);if(c.indexOf('desain')>=0&&/(paket os|ram|cpu|gpu|psu|ssd|hdd|iphone|find hub|windows|office|diagnosis)/i.test(l))throw appError_('VALIDATION_ERROR','Layanan IT tidak cocok dengan kategori desain.');if((c.indexOf('servis')>=0||c.indexOf('it')>=0)&&/(poster|banner|logo|presentasi|media sosial|foto produk)/i.test(l))throw appError_('VALIDATION_ERROR','Layanan desain tidak cocok dengan kategori servis IT.');return{nama:nama,email:email,wa:wa,kategori:kategori,layanan:layanan,os:os,metode:metode,brief:brief,clientRequestId:normalizeClientRequestId_(p.clientRequestId||p['Client Request ID']||'')};}
function analyzeOrder_(layanan,briefText,os){const selected=String(layanan||'').split(/\s*,\s*/).filter(Boolean),brief=String(briefText||'').toLowerCase();let base=0,min=0,max=0,known=0;selected.forEach(function(i){const key=resolveService_(i);if(key){const c=SERVICE_CATALOG[key];base+=c.base;min+=c.min;max+=c.max;known++;}});if(!base){base=/servis|diagnosis|os|windows|ubuntu|debian|kali|ram|cpu|gpu|psu|ssd|hdd|iphone|find hub/i.test(layanan)?85000:20000;min=base;max=base;}let mult=1,days=2,priority='Normal',risks=[];if(/hari ini|besok|urgent|mendesak|secepatnya/.test(brief)){mult*=1.1;days=1;priority='Tinggi';risks.push('deadline-mendesak');}if(/kompleks|animasi|3d|banyak halaman|branding lengkap|revisi banyak/.test(brief)){mult*=1.15;days+=2;if(priority!=='Tinggi')priority='Menengah';risks.push('brief-kompleks');}if(/sederhana|simple|ringan|satu halaman|satu desain/.test(brief)){mult*=.95;days=Math.max(1,days-1);if(priority==='Normal')priority='Rendah';}if(selected.length>1){mult*=1.05;days+=Math.min(2,selected.length-1);risks.push('multi-layanan');}const quality=calculateBriefQuality_(briefText);if(quality<50)risks.push('brief-perlu-diperjelas');if(!os&&/paket os|windows|ubuntu|debian|kali/i.test(layanan))risks.push('OS-belum-dipilih');if(known<selected.length)risks.push('layanan-tidak-dikenal');const estimate=Math.max(5000,Math.round(base*mult/5000)*5000);return{estimate:estimate,min:Math.round(min*mult/5000)*5000,max:Math.round(max*mult/5000)*5000,priority:priority,days:days,quality:quality,risks:risks,summary:'base='+base+', mult='+mult.toFixed(2)+', known='+known+'/'+selected.length};}
function calculateBriefQuality_(b){const s=String(b||'').trim();let q=s?20:0;if(s.length>=30)q+=15;if(s.length>=80)q+=15;if(s.length>=160)q+=10;if(/ukuran|size|dimensi|px|cm|mm/i.test(s))q+=10;if(/deadline|tenggat|tanggal|besok|hari/i.test(s))q+=10;if(/referensi|contoh|warna|brand|target|tujuan/i.test(s))q+=15;if(/format|png|jpg|pdf|pptx|ai|psd|svg/i.test(s))q+=5;return Math.min(100,q);}
function verifyOrder_(id,name,email,rid){const o=findOrderById_(id);if(!o)return errorObject_('NOT_FOUND','Pesanan tidak ditemukan.',rid);if(!safeEqual_(normalizeIdentityName_(name),normalizeIdentityName_(o.nama))||!safeEqual_(normalizeEmail_(email),normalizeEmail_(o.email))){writeAudit_(rid,'public','VERIFY_ORDER',o.id,'DENIED','Nama/email tidak cocok.');return errorObject_('VERIFICATION_FAILED','Nama dan email tidak cocok dengan pesanan.',rid);}const token=makeToken_();CacheService.getScriptCache().put('verify-order:'+token,JSON.stringify({id:o.id}),APP.VERIFY_SECONDS);writeAudit_(rid,'public','VERIFY_ORDER',o.id,'SUCCESS','Verifikasi berhasil.');return{status:'ok',verified:true,requestId:rid,verificationToken:token,expiresIn:APP.VERIFY_SECONDS,order:verifiedOrder_(o)};}
function getVerifiedOrder_(id,token,rid){const raw=token?CacheService.getScriptCache().get('verify-order:'+String(token)):'';const target=normalizeOrderId_(id);if(!target||!raw)return errorObject_('VERIFICATION_REQUIRED','Verifikasi diperlukan.',rid);let x;try{x=JSON.parse(raw);}catch(_){return errorObject_('VERIFICATION_INVALID','Token tidak valid.',rid);}if(x.id!==target)return errorObject_('VERIFICATION_MISMATCH','Token tidak cocok.',rid);const o=findOrderById_(target);return o?{status:'ok',verified:true,requestId:rid,order:verifiedOrder_(o)}:errorObject_('NOT_FOUND','Pesanan tidak ditemukan.',rid);}
function publicOrder_(o){return{id:o.id,nama:maskName_(o.nama),email:maskEmail_(o.email),layanan:o.layanan,kategori:o.kategori,status:o.status,tenggat:o.tenggat||'—',verificationRequired:true};}
function verifiedOrder_(o){return{id:o.id,tanggal:o.tanggal,updated:o.updated,nama:o.nama,email:o.email,kontak:o.kontak,kategori:o.kategori,layanan:o.layanan,os:o.os,metode:o.metode,brief:o.brief,tenggat:o.tenggat,status:o.status,estimasi:o.estimasi,payment:o.payment,revisi:o.revisi,link:o.link,priority:o.priority,days:o.days,invoice:{number:o.id,date:o.tanggal,customer:o.nama,email:o.email,phone:o.kontak,service:o.layanan,amount:o.estimasi,payment:o.payment,status:o.status}};}
function findOrderRow_(id){const s=getOrdersSheet_(),target=normalizeOrderId_(id);if(!target||s.getLastRow()<2)return null;const ids=s.getRange(2,1,s.getLastRow()-1,1).getDisplayValues().flat();for(let i=0;i<ids.length;i++)if(String(ids[i]).trim().toUpperCase()===target)return{sheet:s,row:i+2,id:target,values:s.getRange(i+2,1,1,ORDER_HEADERS.length).getValues()[0]};return null;}
function findOrderById_(id){const f=findOrderRow_(id);return f?rowToOrder_(f.values,f.row):null;}
function getOrdersSheet_(){const ss=getSpreadsheet_();let s=ss.getSheetByName(SHEETS.ORDERS);if(!s){setupBackend();s=ss.getSheetByName(SHEETS.ORDERS);}if(!s)throw appError_('SHEET_NOT_FOUND','Orders tidak ditemukan.');return s;}
function nextOrderId_(s){const p=PropertiesService.getScriptProperties();let n=Number(p.getProperty('TA_ORDER_SEQ')||0);if(!n)n=findMaxOrderNumber_(s);n++;p.setProperty('TA_ORDER_SEQ',String(n));return APP.ORDER_PREFIX+String(n).padStart(APP.ORDER_WIDTH,'0');}
function findMaxOrderNumber_(s){if(!s||s.getLastRow()<2)return 0;return s.getRange(2,1,s.getLastRow()-1,1).getDisplayValues().flat().reduce((m,v)=>{const a=String(v||'').match(/(\d+)$/);return Math.max(m,a?Number(a[1]):0);},0);}
function recentOrders_(s,n){if(s.getLastRow()<2)return[];const last=s.getLastRow(),size=Math.min(Math.max(Number(n)||APP.PAGE_SIZE,1),APP.MAX_PAGE_SIZE),start=Math.max(2,last-size+1);return s.getRange(start,1,last-start+1,ORDER_HEADERS.length).getValues().reverse().filter(r=>r[0]).map(r=>rowToOrder_(r));}
function searchOrders_(s,q){if(s.getLastRow()<2)return[];const t=normalizeSearch_(q),rows=s.getRange(2,1,s.getLastRow()-1,ORDER_HEADERS.length).getValues();return rows.filter(r=>normalizeSearch_([r[0],r[3],r[4],r[5],r[6],r[7],r[10],r[12]].join(' ')).indexOf(t)>=0).reverse().slice(0,APP.MAX_PAGE_SIZE).map(r=>rowToOrder_(r));}
function rowToOrder_(r,row){return{row:row,id:valueString_(r[0]),tanggal:formatDateTimeValue_(r[1]),updated:formatDateTimeValue_(r[2]),nama:valueString_(r[3]),email:valueString_(r[4]),kontak:valueString_(r[5]),kategori:valueString_(r[6]),layanan:valueString_(r[7]),os:valueString_(r[8]),metode:valueString_(r[9]),brief:valueString_(r[10]),tenggat:formatDateValue_(r[11]),status:valueString_(r[12])||'Pending',estimasi:parseNumber_(r[13]),payment:valueString_(r[14])||'Belum Bayar',revisi:parseNumber_(r[15]),link:valueString_(r[16]),priority:valueString_(r[17])||'Normal',days:r[18]===''?computeDaysLeft_(r[11]):parseNumber_(r[18]),source:valueString_(r[19]),clientRequestId:valueString_(r[20]),note:valueString_(r[21])};}
function dashboardStats_(s){const z={totalPesanan:0,pending:0,proses:0,review:0,selesai:0,dibatalkan:0,terlambat:0,estimasiRevenue:0,bulanIni:0,lunas:0,menungguPembayaran:0,revisiAktif:0};if(s.getLastRow()<2)return z;const month=Utilities.formatDate(new Date(),APP.TIMEZONE,'yyyy-MM'),rows=s.getRange(2,1,s.getLastRow()-1,ORDER_HEADERS.length).getValues();rows.forEach(r=>{if(!r[0])return;z.totalPesanan++;const st=normalizeSearch_(r[12]),pay=normalizeSearch_(r[14]);if(st==='pending')z.pending++;else if(st==='proses')z.proses++;else if(st==='review')z.review++;else if(st==='selesai')z.selesai++;else if(st==='dibatalkan')z.dibatalkan++;if(pay==='lunas')z.lunas++;if(pay==='belum bayar')z.menungguPembayaran++;z.estimasiRevenue+=parseNumber_(r[13]);z.revisiAktif+=parseNumber_(r[15]);const d=r[1] instanceof Date?r[1]:new Date(r[1]);if(!isNaN(d.getTime())&&Utilities.formatDate(d,APP.TIMEZONE,'yyyy-MM')===month)z.bulanIni++;const left=computeDaysLeft_(r[11]);if(left!==''&&left<0&&st!=='selesai'&&st!=='dibatalkan')z.terlambat++;});return z;}
function getPublicStats_(){const c=CacheService.getScriptCache(),hit=c.get('ta:stats');if(hit)try{return JSON.parse(hit);}catch(_){}const s=dashboardStats_(getOrdersSheet_()),d={totalPesanan:s.totalPesanan,selesai:s.selesai};c.put('ta:stats',JSON.stringify(d),60);return d;}
function upsertCustomer_(i,id,now){const s=getOrCreateSheet_(getSpreadsheet_(),SHEETS.CUSTOMERS,CUSTOMER_HEADERS),last=s.getLastRow();if(last<2){s.appendRow(['CUS-'+makeToken_().slice(0,8),now,now,safeCell_(i.nama),safeCell_(i.email),safeCell_(i.wa),1,id,'Aktif','']);return;}const rows=s.getRange(2,1,last-1,CUSTOMER_HEADERS.length).getValues(),email=normalizeEmail_(i.email);let idx=-1;for(let n=0;n<rows.length;n++)if(normalizeEmail_(rows[n][4])===email){idx=n;break;}if(idx<0)s.appendRow(['CUS-'+makeToken_().slice(0,8),now,now,safeCell_(i.nama),safeCell_(i.email),safeCell_(i.wa),1,id,'Aktif','']);else{const rn=idx+2;s.getRange(rn,3).setValue(now);s.getRange(rn,4).setValue(safeCell_(i.nama));s.getRange(rn,6).setValue(safeCell_(i.wa));s.getRange(rn,7).setValue(parseNumber_(rows[idx][6])+1);s.getRange(rn,8).setValue(id);}}
function findRequest_(id){if(!id)return'';const s=getSpreadsheet_().getSheetByName(SHEETS.REQUESTS);if(!s||s.getLastRow()<2)return'';const rows=s.getRange(2,1,s.getLastRow()-1,2).getValues(),t=String(id);for(let i=rows.length-1;i>=0;i--)if(String(rows[i][0])===t)return String(rows[i][1]);return'';}
function saveRequest_(id,orderId,rid){getOrCreateSheet_(getSpreadsheet_(),SHEETS.REQUESTS,REQUEST_HEADERS).appendRow([safeCell_(id),safeCell_(orderId),new Date(),hash_(id+'|'+orderId+'|'+rid,'request')]);}
function getSpreadsheet_(){const p=PropertiesService.getScriptProperties(),id=p.getProperty('TA_SPREADSHEET_ID');if(id)return SpreadsheetApp.openById(id);const ss=SpreadsheetApp.getActiveSpreadsheet();if(!ss)throw appError_('SPREADSHEET_NOT_FOUND','Spreadsheet aktif tidak ditemukan.');return ss;}
function setSpreadsheetId(){const ui=SpreadsheetApp.getUi(),r=ui.prompt('Spreadsheet ID','Masukkan Spreadsheet ID database.',ui.ButtonSet.OK_CANCEL);if(r.getSelectedButton()!==ui.Button.OK)return;const id=String(r.getResponseText()||'').trim();if(!/^[A-Za-z0-9_-]{20,}$/.test(id))return ui.alert('Spreadsheet ID tidak valid.');PropertiesService.getScriptProperties().setProperty('TA_SPREADSHEET_ID',id);ui.alert('Spreadsheet ID tersimpan.');}
function validatePayloadSize_(p){if(JSON.stringify(p||{}).length>APP.MAX_BODY_BYTES)throw appError_('PAYLOAD_TOO_LARGE','Data terlalu besar.');}
function enforceRate_(key,max,win){if(!checkRate_(key,max,win))throw appError_('RATE_LIMITED','Terlalu banyak permintaan. Tunggu beberapa menit lalu coba lagi.');}
function checkRate_(key,max,win){const c=CacheService.getScriptCache(),k='rate:'+hashShort_(key),n=Number(c.get(k)||0);if(n>=max)return false;c.put(k,String(n+1),win);return true;}
function normalizeOrderId_(v){let x=String(v||'').trim().toUpperCase().replace(/^ORD[-\s]?/,'');if(!/^\d{1,12}$/.test(x))return'';return APP.ORDER_PREFIX+x.padStart(APP.ORDER_WIDTH,'0');}
function normalizeClientRequestId_(v){const x=sanitizePlain_(v,100);if(!x)return'';if(!/^[A-Za-z0-9._:-]{8,100}$/.test(x))throw appError_('VALIDATION_ERROR','Client Request ID tidak valid.');return x;}
function sanitizePlain_(v,max){let x=String(v==null?'':v).replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim();return x.length>max?x.slice(0,max):x;}
function safeCell_(v){const x=String(v==null?'':v);return/^[=+\-@]/.test(x)?"'"+x:x;}
function normalizeEmail_(v){return String(v||'').trim().toLowerCase();}function normalizeIdentityName_(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ');}function normalizeSearch_(v){return String(v==null?'':v).toLowerCase().trim();}
function hasOwn_(o,k){return Object.prototype.hasOwnProperty.call(o,k);}function validateEnum_(v,a,l){const x=sanitizePlain_(v,120);if(a.indexOf(x)<0)throw appError_('VALIDATION_ERROR',l+' tidak valid.');return x;}function clampInt_(v,min,max,l){const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw appError_('VALIDATION_ERROR',l+' tidak valid.');return n;}
function computeDaysLeft_(v){if(!v)return'';const d=v instanceof Date?v:new Date(v);if(isNaN(d.getTime()))return'';const t=new Date(),a=new Date(t.getFullYear(),t.getMonth(),t.getDate()),b=new Date(d.getFullYear(),d.getMonth(),d.getDate());return Math.ceil((b-a)/86400000);}function addBusinessDays_(d,n){const x=new Date(d.getTime());let r=Number(n)||0;while(r>0){x.setDate(x.getDate()+1);const w=x.getDay();if(w!==0&&w!==6)r--;}return x;}
function parseDateInput_(v,l){const d=new Date(String(v||''));if(!String(v||'')||isNaN(d.getTime()))throw appError_('VALIDATION_ERROR',l+' tidak valid.');return d;}function formatDate_(v){const d=v instanceof Date?v:new Date(v);return isNaN(d.getTime())?'':Utilities.formatDate(d,APP.TIMEZONE,'dd/MM/yyyy');}function formatDateTime_(v){return Utilities.formatDate(v instanceof Date?v:new Date(v),APP.TIMEZONE,'dd/MM/yyyy HH:mm:ss');}function formatDateTimeValue_(v){if(!v)return'';try{return formatDateTime_(v);}catch(_){return String(v);}}function formatDateValue_(v){if(!v)return'';try{return formatDate_(v);}catch(_){return String(v);}}
function formatRupiah_(n){return String(Math.round(parseNumber_(n))).replace(/\B(?=(\d{3})+(?!\d))/g,'.');}function parseNumber_(v){if(typeof v==='number')return isNaN(v)?0:v;const n=Number(String(v==null?'':v).replace(/[^\d.-]/g,''));return isNaN(n)?0:n;}function valueString_(v){return v==null?'':String(v);}
function getParam_(e,k){return e&&e.parameter?String(e.parameter[k]||''):'';}function readBody_(e){const raw=e&&e.postData&&e.postData.contents?String(e.postData.contents):'';if(!raw)throw appError_('EMPTY_BODY','Body permintaan kosong.');if(raw.length>APP.MAX_BODY_BYTES)throw appError_('PAYLOAD_TOO_LARGE','Ukuran permintaan terlalu besar.');try{return JSON.parse(raw);}catch(_){throw appError_('INVALID_JSON','Format JSON tidak valid.');}}
function nowIso_(){return new Date().toISOString();}function makeToken_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');}function makeRequestId_(){return'REQ-'+Date.now().toString(36).toUpperCase()+'-'+makeToken_().slice(0,10).toUpperCase();}
function hash_(v,s){const b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s||'')+':'+String(v||''),Utilities.Charset.UTF_8);return bytesToHex_(b);}function hashPassword_(pw,s){let v=String(s||'')+':'+String(pw||'');for(let i=0;i<2500;i++)v=bytesToHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,v,Utilities.Charset.UTF_8));return v;}function hashShort_(v){return hash_(v,'short').slice(0,20);}function bytesToHex_(a){return a.map(b=>{const n=b<0?b+256:b;return('0'+n.toString(16)).slice(-2)}).join('');}function safeEqual_(a,b){const x=String(a||''),y=String(b||'');if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x.charCodeAt(i)^y.charCodeAt(i);return d===0;}
function errorObject_(c,m,r){return{status:'error',code:c,message:m,requestId:r};}function errorResponse_(c,m,r){return json_(errorObject_(c,m,r));}function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}function jsonResponse_(o){return json_(o);}function appError_(c,m){const e=new Error(m);e.code=c;return e;}
function writeAudit_(rid,a,ac,id,res,d){try{const s=getSpreadsheet_().getSheetByName(SHEETS.AUDIT);if(s)s.appendRow([new Date(),safeCell_(rid),safeCell_(a),safeCell_(ac),safeCell_(id),safeCell_(res),safeCell_(String(d||'').slice(0,1500))]);}catch(_){}}function logError_(rid,a,c,e){try{const s=getSpreadsheet_().getSheetByName(SHEETS.ERRORS);if(s)s.appendRow([new Date(),safeCell_(rid),safeCell_(a),safeCell_(c),safeCell_(String(e&&e.message||e).slice(0,800)),safeCell_(String(e&&e.stack||'').slice(0,2500))]);}catch(_){}}
function writeSetting_(s,k,v,d){if(!s)return;const rows=s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,4).getValues():[],i=rows.findIndex(r=>String(r[0])===k),row=[safeCell_(k),safeCell_(v),safeCell_(d),new Date()];if(i<0)s.appendRow(row);else s.getRange(i+2,1,1,4).setValues([row]);}
function promptSecret_(ui,title,message){return prompt_(ui,title,message);}function promptText_(ui,title,message){return prompt_(ui,title,message);}function prompt_(ui,t,m){const r=ui.prompt(t,m,ui.ButtonSet.OK_CANCEL);return r.getSelectedButton()===ui.Button.OK?r.getResponseText():null;}
function renderAdmin_(){try{return HtmlService.createTemplateFromFile('index').evaluate().setTitle('TA Admin Console').addMetaTag('viewport','width=device-width, initial-scale=1');}catch(_){return HtmlService.createHtmlOutput('<!doctype html><html lang="id"><body style="font-family:system-ui;padding:32px"><h1>Panel admin belum siap</h1><p>Pastikan index.html tersedia di Apps Script.</p></body></html>');}}
