/**
 * Tama Andrea Studio — Backend Core V7.0
 * Sheets-backed public API + private Admin Console.
 * Secrets stay in Script Properties; this file contains no credentials.
 */
const APP=Object.freeze({
  VERSION:'7.0.0',TIMEZONE:'Asia/Jakarta',ORDER_PREFIX:'ORD-',ORDER_WIDTH:4,
  MAX_BODY_BYTES:30000,PAGE_SIZE:25,MAX_PAGE_SIZE:100,
  VERIFIED_TOKEN_SECONDS:900,ADMIN_STAGE_SECONDS:300,ADMIN_SESSION_SECONDS:21600,
  PUBLIC_ORDER_LIMIT:8,VERIFY_LIMIT:5,TRACK_LIMIT:20,WINDOW:600,
  STATUS:['Pending','Proses','Review','Selesai','Dibatalkan'],
  PAYMENT:['Belum Bayar','DP','Lunas','Dibatalkan'],
  PRIORITY:['Rendah','Normal','Menengah','Tinggi'],
  OS:['Windows 11 Home','Windows 11 Pro','Windows 11 Enterprise LTSC 2024','Ubuntu','Debian','Kali Linux'],
  METHOD:['Teknisi datang ke lokasi — Sabtu/Minggu','Saya membawa perangkat — bisa diantar setelah konfirmasi, termasuk malam hari']
});
const SHEETS=Object.freeze({ORDERS:'Orders',CUSTOMERS:'Customers',AUDIT:'Audit_Log',ERRORS:'Error_Log',REQUESTS:'Request_Index',SETTINGS:'Settings',NOTES:'Service_Notes',BOOT:'Boot_Keys',CATALOG:'Service_Catalog'});
const H={
  ORDERS:['ID Pesanan','Tanggal Masuk','Tanggal Update','Nama Lengkap','Alamat Email','Kontak/WA','Kategori Layanan','Layanan Dipilih','Pilihan OS','Metode Layanan','Rincian Brief','Tenggat Waktu','Status','Estimasi Biaya','Status Pembayaran','Jumlah Revisi','Link Hasil','Prioritas Deadline','Hari Tersisa','Sumber','Client Request ID','Catatan Internal'],
  CUSTOMERS:['Customer ID','Pertama Masuk','Terakhir Masuk','Nama','Email','Kontak/WA','Jumlah Pesanan','Order Terakhir','Status Customer','Catatan'],
  AUDIT:['Timestamp','Request ID','Actor','Action','Entity ID','Result','Detail'],ERRORS:['Timestamp','Request ID','Action','Code','Message','Stack'],
  REQUESTS:['Client Request ID','Order ID','Created At','Request Hash'],SETTINGS:['Key','Value','Description','Updated At'],
  NOTES:['Note ID','Kategori','Judul','Ringkasan','Langkah Kerja','Peringatan / Batasan','Updated At'],
  BOOT:['Key ID','Brand','Jenis Perangkat','Model / Motherboard','BIOS / UEFI','Boot Menu','Catatan','Updated At'],
  CATALOG:['Service Key','Nama Layanan','Kategori','Harga Minimum','Harga Dasar','Harga Maksimum','Paket Tetap','Aktif','Deskripsi','Updated At']
};
const DEFAULT_CATALOG=[
['design.poster','Poster & Flyer Digital','design',15000,15000,80000,'TIDAK','YA','Poster/flyer digital atau cetak'],['design.banner','Banner Marketplace','design',20000,20000,80000,'TIDAK','YA','Banner promosi marketplace'],['design.social','Konten Media Sosial','design',20000,20000,85000,'TIDAK','YA','Konten feed/story/media sosial'],['design.logo','Logo Profesional','design',20000,20000,90000,'TIDAK','YA','Logo brand/organisasi/proyek'],['design.presentation','Desain Presentasi','design',20000,20000,85000,'TIDAK','YA','Desain slide presentasi'],['design.product','Edit Foto Produk','design',20000,20000,80000,'TIDAK','YA','Edit dan perapian foto produk'],
['it.os-basic','Paket OS Basic','it',90000,90000,90000,'YA','YA','1 OS + driver dasar + pengujian'],['it.os-office','Paket OS + Office','it',125000,125000,125000,'YA','YA','OS + Office dengan lisensi resmi'],['it.os-backup','Paket OS + Backup','it',135000,135000,135000,'YA','YA','Backup data + instalasi OS'],['it.os-office-backup','Paket OS + Office + Backup','it',160000,160000,160000,'YA','YA','Backup + OS + Office berlisensi'],['it.diagnosis','Diagnosis PC / Laptop','it',35000,35000,35000,'YA','YA','Pemeriksaan masalah boot/startup/storage'],['it.storage','Cek Kesehatan SSD/HDD','it',35000,35000,35000,'YA','YA','Pemeriksaan storage'],['it.backup','Backup Data Sebelum Instal Ulang','it',40000,40000,100000,'TIDAK','YA','Backup selama storage masih terbaca'],['it.driver','Driver & Update Dasar','it',25000,25000,40000,'TIDAK','YA','Instalasi/penyesuaian driver'],['it.compatibility','Cek Kompatibilitas Komponen & Rekomendasi Upgrade','it',25000,25000,75000,'TIDAK','YA','Cek CPU/RAM/SSD/GPU/PSU dan upgrade'],['it.ram','Pasang / Upgrade RAM','it',50000,50000,50000,'YA','YA','Jasa pemasangan komponen pelanggan'],['it.ssd','Pasang SSD / HDD','it',50000,50000,50000,'YA','YA','Jasa pemasangan storage pelanggan'],['it.cpu','Pasang CPU','it',60000,60000,60000,'YA','YA','Jasa pemasangan CPU'],['it.gpu','Pasang GPU','it',60000,60000,60000,'YA','YA','Jasa pemasangan GPU'],['it.psu','Pasang PSU','it',60000,60000,60000,'YA','YA','Jasa pemasangan PSU'],['it.upgrade2','Pasang / Upgrade 2 Komponen','it',90000,90000,90000,'YA','YA','Jasa pemasangan dua komponen'],['it.office','Instal Microsoft Office','it',35000,35000,35000,'YA','YA','Instalasi Office dengan lisensi resmi'],['it.iphone','Restore / Flash iPhone','it',60000,60000,100000,'TIDAK','YA','Restore perangkat pelanggan tanpa bypass Activation Lock'],['it.find-android','Bantuan Find Hub Android','it',35000,35000,75000,'TIDAK','YA','Pendampingan pemilik menggunakan Find Hub'],['it.find-iphone','Bantuan Find My / Lacak iPhone','it',35000,35000,75000,'TIDAK','YA','Pendampingan pemilik menggunakan Find My']
];
function onOpen(){SpreadsheetApp.getUi().createMenu('TA Backend').addItem('Setup / Periksa Backend','setupBackend').addItem('Konfigurasi Admin','configureAdminSecurity').addItem('Health Check','runHealthCheck').addToUi();}
function doGet(e){const rid=rid_();try{const a=param_(e,'action');if(a==='ping')return json_({status:'ok',service:'tama-andrea-studio-backend',version:APP.VERSION,requestId:rid,time:new Date().toISOString()});if(a==='stats')return json_({status:'ok',requestId:rid,data:publicStats_(),updatedAt:dt_(new Date())});if(a==='track'){rate_('track:'+hashShort_(param_(e,'id')),APP.TRACK_LIMIT,APP.WINDOW);const id=orderId_(param_(e,'id'));if(!id)throw err_('VALIDATION_ERROR','ID pesanan tidak valid.');const o=findOrder_(id);if(!o)throw err_('NOT_FOUND','Pesanan tidak ditemukan.');return json_({status:'ok',requestId:rid,order:masked_(o)});}if(a==='admin')return renderAdmin_();return json_({status:'ok',service:'Tama Andrea Studio',version:APP.VERSION,requestId:rid,endpoints:['ping','stats','track','newOrder','verifyOrder','getVerifiedOrder']});}catch(e){logErr_(rid,'GET',e,e.code||'INTERNAL_ERROR');return error_(e.code||'INTERNAL_ERROR',publicMsg_(e),rid,e.retryAfterSeconds||0);}}
function doPost(e){const rid=rid_();let action='unknown';try{const b=body_(e);action=safe_(b.action,60);if(action==='newOrder'){const d=b.data||b;honeypot_(d);const crid=clientId_(b.clientRequestId||d.clientRequestId||'');rate_('order:'+hashShort_(crid||'anon'),APP.PUBLIC_ORDER_LIMIT,APP.WINDOW);return json_(newOrder_(d,{requestId:rid,clientRequestId:crid,source:'website'}));}if(action==='verifyOrder'){const id=b.id||b.orderId||'';rate_('verify:'+hashShort_(id+'|'+String(b.email||'')),APP.VERIFY_LIMIT,APP.WINDOW);return json_(verify_(id,b.name,b.email,rid));}if(action==='getVerifiedOrder')return json_(verifiedFetch_(b.id||b.orderId,b.verificationToken,rid));throw err_('UNKNOWN_ACTION','Action tidak dikenali.');}catch(e){logErr_(rid,action,e,e.code||'INTERNAL_ERROR');return error_(e.code||'INTERNAL_ERROR',publicMsg_(e),rid,e.retryAfterSeconds||0);}}
function setupBackend(){const ss=sheetFile_();Object.keys(SHEETS).forEach(k=>ensure_(ss,SHEETS[k],H[k]));if(getSheet_(SHEETS.CATALOG).getLastRow()<2)seedCatalog_();seedBoot_();seedNotes_();const p=PropertiesService.getScriptProperties(),o=getSheet_(SHEETS.ORDERS);if(!p.getProperty('TA_ORDER_SEQ'))p.setProperty('TA_ORDER_SEQ',String(maxOrder_(o)));const s=getSheet_(SHEETS.SETTINGS);[['BACKEND_VERSION',APP.VERSION,'Backend version'],['PUBLIC_TRACKING','MASKED_UNTIL_VERIFIED','Public tracking masks customer data'],['PUBLIC_CUSTOMER_ACCESS','DENIED','Customers never exposed publicly'],['ADMIN_AUTH','3_LAYER_HASHED_SESSION','Gate/code/identity/password/session'],['PRICING_ENGINE','SERVICE_CATALOG_RULES','Configurable service catalog'],['DATA_RETENTION','ADMIN_CONTROLLED','Retention policy documented in Settings']].forEach(x=>setting_(s,x[0],x[1],x[2]));SpreadsheetApp.flush();return{status:'success',version:APP.VERSION,sheets:Object.keys(SHEETS).map(k=>SHEETS[k]),orderSequence:Number(p.getProperty('TA_ORDER_SEQ')||0)};}
function runHealthCheck(){const r={status:'ok',version:APP.VERSION,time:new Date().toISOString(),sheets:{},config:{},catalog:{}};try{const ss=sheetFile_();Object.keys(SHEETS).forEach(k=>r.sheets[SHEETS[k]]=!!ss.getSheetByName(SHEETS[k]));const p=PropertiesService.getScriptProperties();r.config.adminConfigured=!!p.getProperty('TA_ADMIN_GATE_HASH')&&!!p.getProperty('TA_ADMIN_CODE_HASH')&&!!p.getProperty('TA_ADMIN_PASSWORD_HASH');r.config.orderSequence=Number(p.getProperty('TA_ORDER_SEQ')||0);const c=catalog_();r.catalog.total=c.length;r.catalog.active=c.filter(x=>x.active).length;r.status=Object.keys(r.sheets).every(k=>r.sheets[k])?'ok':'warning';return r;}catch(e){r.status='error';r.error='Health check gagal.';logErr_(rid_(),'health',e,'HEALTH_CHECK_FAILED');return r;}}
function configureAdminSecurity(){const ui=SpreadsheetApp.getUi(),gate=prompt_(ui,'Tahap 1 — Kode Gerbang Admin'),code=prompt_(ui,'Tahap 2 — Kode Akses Admin'),name=prompt_(ui,'Tahap 3 — Nama Admin'),email=prompt_(ui,'Tahap 3 — Email Admin'),pass=prompt_(ui,'Tahap 3 — Password Admin');if([gate,code,name,email,pass].some(v=>v===null))return;const n=normalizeId_(name),e=String(email).trim().toLowerCase();if(String(gate).trim().length<12||String(code).trim().length<12||String(pass).length<12||gate===code||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)||n.length<2){ui.alert('Konfigurasi tidak valid. Kode minimal 12 karakter, password minimal 12 karakter, nama/email harus valid.');return;}const p=PropertiesService.getScriptProperties(),gs=token_(),cs=token_(),ps=token_(),is=token_();p.setProperties({TA_ADMIN_GATE_SALT:gs,TA_ADMIN_GATE_HASH:hash_(String(gate).trim(),gs),TA_ADMIN_CODE_SALT:cs,TA_ADMIN_CODE_HASH:hash_(String(code).trim(),cs),TA_ADMIN_ID_SALT:is,TA_ADMIN_NAME_HASH:hash_(n,is),TA_ADMIN_EMAIL_HASH:hash_(e,is),TA_ADMIN_PASSWORD_SALT:ps,TA_ADMIN_PASSWORD_HASH:hash_(String(pass),ps),TA_ADMIN_CONFIGURED_AT:new Date().toISOString()},true);ui.alert('Konfigurasi admin tersimpan. Secret tidak ditulis ke GitHub.');writeAudit_(rid_(),'admin-setup','CONFIGURE_SECURITY','','SUCCESS','Admin security diperbarui.');}
function prompt_(ui,title){const r=ui.prompt(title,'Masukkan nilai untuk tahap ini.',ui.ButtonSet.OK_CANCEL);return r.getSelectedButton()===ui.Button.OK?String(r.getResponseText()||''):null;}
function adminGate(v){const rid=rid_();try{rate_('admin-gate',5,APP.WINDOW);const p=PropertiesService.getScriptProperties(),s=p.getProperty('TA_ADMIN_GATE_SALT'),h=p.getProperty('TA_ADMIN_GATE_HASH');if(!s||!h)throw err_('ADMIN_NOT_CONFIGURED','Admin belum dikonfigurasi.');if(!safeEq_(hash_(String(v||'').trim(),s),h))throw retryErr_('GATE_DENIED','Kode gerbang tidak valid.',180);const t=token_();CacheService.getScriptCache().put('ta:gate:'+t,'1',APP.ADMIN_STAGE_SECONDS);return{status:'ok',stageToken:t,expiresIn:APP.ADMIN_STAGE_SECONDS,requestId:rid};}catch(e){return failAdmin_(rid,'adminGate',e);}}
function adminCode(t,v){const rid=rid_();try{if(!CacheService.getScriptCache().get('ta:gate:'+t))throw err_('STAGE_EXPIRED','Tahap pertama kedaluwarsa.');rate_('admin-code:'+hashShort_(t),5,APP.WINDOW);const p=PropertiesService.getScriptProperties(),s=p.getProperty('TA_ADMIN_CODE_SALT'),h=p.getProperty('TA_ADMIN_CODE_HASH');if(!s||!h)throw err_('ADMIN_NOT_CONFIGURED','Kode akses belum dikonfigurasi.');if(!safeEq_(hash_(String(v||'').trim(),s),h))throw retryErr_('CODE_DENIED','Kode akses admin tidak valid.',180);CacheService.getScriptCache().remove('ta:gate:'+t);const x=token_();CacheService.getScriptCache().put('ta:verify:'+x,'1',APP.ADMIN_STAGE_SECONDS);return{status:'ok',verifyToken:x,expiresIn:APP.ADMIN_STAGE_SECONDS,requestId:rid};}catch(e){return failAdmin_(rid,'adminCode',e);}}
function adminVerify(t,payload){const rid=rid_();try{if(!CacheService.getScriptCache().get('ta:verify:'+t))throw err_('STAGE_EXPIRED','Tahap verifikasi kedaluwarsa.');rate_('admin-verify:'+hashShort_(t),5,APP.WINDOW);const p=PropertiesService.getScriptProperties(),is=p.getProperty('TA_ADMIN_ID_SALT'),nh=p.getProperty('TA_ADMIN_NAME_HASH'),eh=p.getProperty('TA_ADMIN_EMAIL_HASH'),ps=p.getProperty('TA_ADMIN_PASSWORD_SALT'),ph=p.getProperty('TA_ADMIN_PASSWORD_HASH');if(!is||!nh||!eh||!ps||!ph)throw err_('ADMIN_NOT_CONFIGURED','Identitas/password admin belum dikonfigurasi.');const name=normalizeId_(payload&&payload.name),email=String(payload&&payload.email||'').trim().toLowerCase(),pass=String(payload&&payload.password||'');if(!safeEq_(hash_(name,is),nh)||!safeEq_(hash_(email,is),eh)||!safeEq_(hash_(pass,ps),ph))throw retryErr_('AUTH_FAILED','Nama, email, atau password admin tidak cocok.',300);CacheService.getScriptCache().remove('ta:verify:'+t);const s=token_();CacheService.getScriptCache().put('ta:admin:'+s,'1',APP.ADMIN_SESSION_SECONDS);writeAudit_(rid,'admin','LOGIN','','SUCCESS','Admin login berhasil.');return{status:'ok',token:s,expiresIn:APP.ADMIN_SESSION_SECONDS,adminName:String(payload.name||'Admin').trim(),requestId:rid};}catch(e){return failAdmin_(rid,'adminVerify',e);}}
function adminLogoutSecure(t){if(t)CacheService.getScriptCache().remove('ta:admin:'+String(t));return{status:'ok'};}
function requireAdmin_(t){if(!t||!CacheService.getScriptCache().get('ta:admin:'+String(t)))throw err_('ADMIN_SESSION_EXPIRED','Sesi admin kedaluwarsa. Silakan login lagi.');}
function failAdmin_(rid,a,e){logErr_(rid,a,e,e.code||'INTERNAL_ERROR');return errorObj_(e.code||'INTERNAL_ERROR',publicMsg_(e),rid,e.retryAfterSeconds||0);}
function getDashboardData(q,t){requireAdmin_(t);const s=getSheet_(SHEETS.ORDERS),term=safe_(q,120);return{status:'ok',version:APP.VERSION,stats:dashboardStats_(s),orders:term?searchOrders_(s,term):recentOrders_(s,APP.PAGE_SIZE),customerCount:customerCount_(),updatedAt:dt_(new Date())};}
function getCustomers(t,q){requireAdmin_(t);const s=getSheet_(SHEETS.CUSTOMERS);if(s.getLastRow()<2)return{status:'ok',customers:[]};const term=normalize_(q),rows=s.getRange(2,1,s.getLastRow()-1,H.CUSTOMERS.length).getValues();const out=rows.filter(r=>!term||normalize_([r[0],r[3],r[4],r[5],r[8]].join(' ')).indexOf(term)!==-1).slice(0,APP.MAX_PAGE_SIZE).map(r=>({id:String(r[0]),nama:String(r[3]),email:String(r[4]),wa:String(r[5]),jumlah:Number(r[6]||0),orderTerakhir:String(r[7]),status:String(r[8]),catatan:String(r[9]||'')}));return{status:'ok',customers:out};}
function updateOrderFromConsole(id,p,t){requireAdmin_(t);const f=findOrderRow_(orderId_(id));if(!f)throw err_('NOT_FOUND','Pesanan tidak ditemukan.');const x=p||{},r=f.values.slice();if(has_(x,'status'))r[12]=enum_(x.status,APP.STATUS,'Status');if(has_(x,'payment'))r[14]=enum_(x.payment,APP.PAYMENT,'Status pembayaran');if(has_(x,'statusPembayaran'))r[14]=enum_(x.statusPembayaran,APP.PAYMENT,'Status pembayaran');if(has_(x,'revisi'))r[15]=int_(x.revisi,0,99,'Revisi');if(has_(x,'jumlahRevisi'))r[15]=int_(x.jumlahRevisi,0,99,'Revisi');if(has_(x,'priority'))r[17]=enum_(x.priority,APP.PRIORITY,'Prioritas');if(has_(x,'prioritas'))r[17]=enum_(x.prioritas,APP.PRIORITY,'Prioritas');if(has_(x,'link'))r[16]=safeCell_(x.link);if(has_(x,'note'))r[21]=safeCell_(x.note);if(has_(x,'catatan'))r[21]=safeCell_(x.catatan);if(has_(x,'tenggat'))r[11]=parseDate_(x.tenggat);r[2]=new Date();r[18]=daysLeft_(r[11]);f.sheet.getRange(f.row,1,1,H.ORDERS.length).setValues([r]);writeAudit_(rid_(),'admin','UPDATE_ORDER',f.values[0],'SUCCESS','Order diperbarui.');return{status:'ok',order:rowOrder_(r,f.row)};}
function deleteOrderFromConsole(id,t){requireAdmin_(t);const f=findOrderRow_(orderId_(id));if(!f)throw err_('NOT_FOUND','Pesanan tidak ditemukan.');f.sheet.deleteRow(f.row);writeAudit_(rid_(),'admin','DELETE_ORDER',f.values[0],'SUCCESS','Order dihapus.');return{status:'ok',id:f.values[0]};}
function analyzeBriefFromConsole(service,brief,t){requireAdmin_(t);return analyze_(service,brief,'');}
function getServiceNotes(t,q,c){requireAdmin_(t);const s=getSheet_(SHEETS.NOTES);if(s.getLastRow()<2)return{status:'ok',notes:[]};const Q=normalize_(q),C=normalize_(c),rows=s.getRange(2,1,s.getLastRow()-1,H.NOTES.length).getValues();return{status:'ok',notes:rows.filter(r=>(!Q||normalize_([r[0],r[1],r[2],r[3],r[4]].join(' ')).indexOf(Q)!==-1)&&(!C||normalize_(r[1])===C)).slice(0,100).map(noteRow_)};}
function saveServiceNote(n,t){requireAdmin_(t);const s=getSheet_(SHEETS.NOTES),x=n||{},id=safeCell_(x.id||('NOTE-'+token_().slice(0,10)));const row=[id,safeCell_(x.category||'Umum'),safeCell_(x.title||'Catatan'),safeCell_(x.summary||''),safeCell_(x.steps||''),safeCell_(x.warnings||''),new Date()];upsertRow_(s,H.NOTES.length,id,0,row);writeAudit_(rid_(),'admin','SAVE_NOTE',id,'SUCCESS','Catatan servis disimpan.');return{status:'ok',note:noteRow_(row)};}
function deleteServiceNote(id,t){requireAdmin_(t);deleteByKey_(SHEETS.NOTES,id,0,'DELETE_NOTE');return{status:'ok',id:id};}
function getBootKeys(t,q,type){requireAdmin_(t);const s=getSheet_(SHEETS.BOOT);if(s.getLastRow()<2)return{status:'ok',items:[]};const Q=normalize_(q),T=normalize_(type),rows=s.getRange(2,1,s.getLastRow()-1,H.BOOT.length).getValues();return{status:'ok',items:rows.filter(r=>(!Q||normalize_([r[1],r[2],r[3],r[4],r[5]].join(' ')).indexOf(Q)!==-1)&&(!T||normalize_(r[2])===T)).slice(0,100).map(bootRow_)};}
function saveBootKey(x,t){requireAdmin_(t);const s=getSheet_(SHEETS.BOOT),n=x||{},id=safeCell_(n.keyId||('BOOT-'+token_().slice(0,10)));const row=[id,safeCell_(n.brand||''),safeCell_(n.type||''),safeCell_(n.model||''),safeCell_(n.bios||''),safeCell_(n.boot||''),safeCell_(n.notes||''),new Date()];upsertRow_(s,H.BOOT.length,id,0,row);writeAudit_(rid_(),'admin','SAVE_BOOT',id,'SUCCESS','Referensi boot disimpan.');return{status:'ok',item:bootRow_(row)};}
function deleteBootKey(id,t){requireAdmin_(t);deleteByKey_(SHEETS.BOOT,id,0,'DELETE_BOOT');return{status:'ok',id:id};}
function getServiceCatalog(t){requireAdmin_(t);return{status:'ok',catalog:catalog_()};}
function saveServiceCatalog(x,t){requireAdmin_(t);const s=getSheet_(SHEETS.CATALOG),n=x||{},key=safe_(n.key,80);if(!key)throw err_('VALIDATION_ERROR','Service key wajib diisi.');const min=int_(n.min,0,100000000,'Harga minimum'),base=int_(n.base,0,100000000,'Harga dasar'),max=int_(n.max,base,100000000,'Harga maksimum');if(min>base||base>max)throw err_('VALIDATION_ERROR','Harga harus minimum ≤ dasar ≤ maksimum.');const row=[key,safe_(n.name,150),safe_(n.category,60),min,base,max,n.fixed?'YA':'TIDAK',n.active===false?'TIDAK':'YA',safe_(n.description,500),new Date()];upsertRow_(s,H.CATALOG.length,key,0,row);writeAudit_(rid_(),'admin','SAVE_CATALOG',key,'SUCCESS','Katalog layanan diperbarui.');return{status:'ok',item:catalogRow_(row)};}
function getAdminSettings(t){requireAdmin_(t);const s=getSheet_(SHEETS.SETTINGS);if(s.getLastRow()<2)return{status:'ok',settings:[]};return{status:'ok',settings:s.getRange(2,1,s.getLastRow()-1,4).getDisplayValues().map(r=>({key:r[0],value:r[1],description:r[2],updatedAt:r[3]}))};}
function updateAdminSetting(k,v,t){requireAdmin_(t);if(!/^[A-Z0-9_]{2,80}$/.test(String(k||'')))throw err_('VALIDATION_ERROR','Key setting tidak valid.');if(/^TA_ADMIN_/.test(k))throw err_('FORBIDDEN','Secret admin tidak dikelola dari dashboard.');setting_(getSheet_(SHEETS.SETTINGS),k,safe_(v,1000),'Dikelola Admin Console.');writeAudit_(rid_(),'admin','UPDATE_SETTING',k,'SUCCESS','Setting diperbarui.');return{status:'ok'};}
function getAuditRecent(t,n){requireAdmin_(t);return{status:'ok',items:recentLogs_(SHEETS.AUDIT,n||50)};}
function getErrorRecent(t,n){requireAdmin_(t);return{status:'ok',items:recentLogs_(SHEETS.ERRORS,n||50)};}
function adminExtendedHealthCheck(t){requireAdmin_(t);const r=runHealthCheck();r.adminSession=true;r.recommendations=[];if(!r.config.adminConfigured)r.recommendations.push('Konfigurasi admin belum lengkap.');if(r.catalog.active===0)r.recommendations.push('Tidak ada service aktif.');return r;}
function newOrder_(p,m){const input=normalizeInput_(p||{});if(m.clientRequestId)input.clientRequestId=clientId_(m.clientRequestId);if(input.clientRequestId){const old=findRequest_(input.clientRequestId);if(old){const e=findOrder_(old);return{status:'ok',duplicate:true,id:old,orderId:old,estimate:e?e.estimasi:0,deadline:e?e.tenggat:'',priority:e?e.prioritas:'Normal'};}}const a=analyze_(input.layanan,input.brief,input.os),lock=LockService.getScriptLock();lock.waitLock(15000);try{const s=getSheet_(SHEETS.ORDERS),id=nextOrder_(s),now=new Date(),due=addBusinessDays_(now,a.days),r=new Array(H.ORDERS.length).fill('');r[0]=id;r[1]=now;r[2]=now;r[3]=safeCell_(input.nama);r[4]=safeCell_(input.email);r[5]=safeCell_(input.wa);r[6]=safeCell_(input.kategori);r[7]=safeCell_(input.layanan);r[8]=safeCell_(input.os);r[9]=safeCell_(input.metode);r[10]=safeCell_(input.brief);r[11]=due;r[12]='Pending';r[13]=a.estimate;r[14]='Belum Bayar';r[15]=0;r[17]=a.priority;r[18]=a.days;r[19]=safeCell_(m.source||'website');r[20]=safeCell_(input.clientRequestId);r[21]=safeCell_('Analyzer: '+a.summary+' | Risiko: '+(a.risks.join(', ')||'none'));const rn=s.getLastRow()+1;s.getRange(rn,1,1,H.ORDERS.length).setValues([r]);s.getRange(rn,2,1,2).setNumberFormat('dd/MM/yyyy HH:mm');s.getRange(rn,12).setNumberFormat('dd/MM/yyyy');s.getRange(rn,14).setNumberFormat('#,##0');upsertCustomer_(input,id,now);if(input.clientRequestId)saveRequest_(input.clientRequestId,id,m.requestId);writeAudit_(m.requestId,m.source==='admin'?'admin':'public','CREATE_ORDER',id,'SUCCESS','Order dibuat.');return{status:'ok',id:id,orderId:id,requestId:m.requestId,layanan:input.layanan,estimate:'Rp '+fmt_(a.estimate),estimatePrice:a.estimate,estimateMin:a.min,estimateMax:a.max,deadline:formatDate_(due),priority:a.priority,days:a.days,analysis:{qualityScore:a.quality,difficulty:a.difficulty,summary:a.summary}};}finally{lock.releaseLock();}}
function normalizeInput_(p){const x={nama:safe_(p.Nama||p['Nama Lengkap']||'',80),email:String(p.Email||p['Alamat Email']||'').trim().toLowerCase(),wa:String(p.WA||p.WhatsApp||p['Kontak/WA']||'').replace(/[^\d+]/g,''),kategori:safe_(p.Kategori||p['Kategori Layanan']||p['Jenis Desain']||'',60),layanan:safe_(p.Layanan||p['Layanan Dipilih']||p.Service||'',700),os:safe_(p.OS||p['Pilihan OS']||'',80),metode:safe_(p.Metode||p['Metode Layanan']||'',160),brief:safe_(p.Brief||p['Rincian Brief']||p['Keterangan Proyek']||'',5000),clientRequestId:clientId_(p.clientRequestId||p['Client Request ID']||'')};if(x.nama.length<2)throw err_('VALIDATION_ERROR','Nama minimal 2 karakter.');if(!/^\S+@\S+\.\S+$/.test(x.email))throw err_('VALIDATION_ERROR','Format email tidak valid.');if(x.wa&&!/^\+?\d{8,15}$/.test(x.wa))throw err_('VALIDATION_ERROR','Nomor WhatsApp tidak valid.');if(x.layanan.length<2)throw err_('VALIDATION_ERROR','Layanan belum dipilih.');if(x.brief.length<5)throw err_('VALIDATION_ERROR','Keterangan terlalu singkat.');if(x.os&&APP.OS.indexOf(x.os)<0)throw err_('VALIDATION_ERROR','Pilihan OS tidak dikenali.');if(x.metode&&APP.METHOD.indexOf(x.metode)<0)throw err_('VALIDATION_ERROR','Metode layanan tidak dikenali.');verifySensitive_(x.brief);return x;}
function analyze_(service,brief,os){const c=catalog_(),items=String(service||'').split(',').map(x=>x.trim()).filter(Boolean);let base=0,min=0,max=0,known=0,fixed=true;items.forEach(it=>{const m=c.find(x=>x.active&&(it.indexOf(x.name)>=0||x.name.indexOf(it)>=0));if(m){base+=m.base;min+=m.min;max+=m.max;known++;fixed=fixed&&m.fixed;}});if(!base){base=90000;min=base;max=base;fixed=true;}const l=String(brief||'').toLowerCase(),urgent=['urgent','besok','segera','mendesak','hari ini'].some(k=>l.indexOf(k)>=0),complex=['3d','animasi','banyak halaman','branding lengkap','revisi banyak','kompleks'].some(k=>l.indexOf(k)>=0),light=['sederhana','simple','simpel','ringan','satu halaman','satu desain'].some(k=>l.indexOf(k)>=0);let mult=1,priority='Normal',days=3,risks=[];if(urgent){mult*=1.1;priority='Tinggi';days=1;risks.push('deadline-mendesak');}if(complex){mult*=1.15;if(priority!=='Tinggi')priority='Menengah';days+=2;risks.push('brief-kompleks');}if(light){mult*=.95;days=Math.max(1,days-1);if(!urgent&&!complex)priority='Rendah';}if(fixed)mult=1;const q=quality_(brief);if(q<50)risks.push('brief-perlu-diperjelas');if(!os&&/OS|Windows|Ubuntu|Debian|Kali|install|instal/i.test(service||''))risks.push('OS-belum-dipilih');if(known<items.length)risks.push('layanan-tidak-dikenal');const estimate=Math.round(base*mult/1000)*1000;return{estimate:estimate,min:Math.round(min*mult/1000)*1000,max:Math.round(max*mult/1000)*1000,priority:priority,days:days,quality:q,difficulty:complex?'Kompleks':(light?'Ringan':'Normal'),risks:risks,summary:['base='+base,'mult='+mult.toFixed(2),'quality='+q,'known='+known+'/'+items.length].join(', ')};}
function quality_(b){const t=String(b||'').trim();if(!t)return 0;let s=20;if(t.length>=30)s+=15;if(t.length>=80)s+=15;if(t.length>=160)s+=10;if(/ukuran|size|dimensi|px|cm|mm/i.test(t))s+=10;if(/deadline|tenggat|tanggal|besok|hari/i.test(t))s+=10;if(/referensi|contoh|warna|brand|target|tujuan/i.test(t))s+=15;if(/png|jpg|pdf|pptx|ai|psd|svg/i.test(t))s+=5;return Math.min(100,s);}
function verifySensitive_(t){if(/password|passcode|kata sandi|OTP|recovery\s*code|api[_ -]?key|access[_ -]?token|private key/i.test(String(t||'')))throw err_('SENSITIVE_INPUT','Jangan masukkan password, OTP, recovery code, token, atau private key.');}
function honeypot_(d){if(String(d.address||d._gotcha||'').trim())throw err_('BOT_SUSPECTED','Permintaan otomatis tidak dapat diproses.');}
function verifiedFetch_(id,t,rid){const x=orderId_(id),stored=CacheService.getScriptCache().get('ta:verified:'+String(t||''));if(!x||stored!==x)throw retryErr_('VERIFICATION_EXPIRED','Verifikasi kedaluwarsa. Cari dan verifikasi ulang.',120);const o=findOrder_(x);if(!o)throw err_('NOT_FOUND','Pesanan tidak ditemukan.');return{status:'ok',requestId:rid,order:verified_(o)};}
function verify_(id,name,email,rid){const x=orderId_(id),o=findOrder_(x);if(!x||!o)throw err_('NOT_FOUND','Pesanan tidak ditemukan.');const n=normalizeId_(name),e=String(email||'').trim().toLowerCase();if(n!==normalizeId_(o.nama)||e!==String(o.email||'').trim().toLowerCase())throw retryErr_('VERIFY_FAILED','Nama dan email tidak cocok.',180);const t=token_();CacheService.getScriptCache().put('ta:verified:'+t,x,APP.VERIFIED_TOKEN_SECONDS);return{status:'ok',requestId:rid,verificationToken:t,expiresIn:APP.VERIFIED_TOKEN_SECONDS,order:verified_(o)};}
function getSheet_(name){const s=sheetFile_().getSheetByName(name);if(!s)throw err_('SETUP_REQUIRED','Sheet '+name+' belum tersedia. Jalankan setupBackend().');return s;}
function sheetFile_(){const p=PropertiesService.getScriptProperties(),id=p.getProperty('TA_SPREADSHEET_ID'),s=id?SpreadsheetApp.openById(id):SpreadsheetApp.getActiveSpreadsheet();if(!s)throw new Error('Spreadsheet tidak ditemukan.');return s;}
function ensure_(ss,name,headers){let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);if(s.getLastRow()===0||s.getLastColumn()<headers.length)s.getRange(1,1,1,headers.length).setValues([headers]);else headers.forEach((h,i)=>{if(String(s.getRange(1,i+1).getDisplayValue()).trim()!==h)s.getRange(1,i+1).setValue(h);});s.setFrozenRows(1);try{s.getRange(1,1,1,headers.length).setFontWeight('bold');}catch(_){ }return s;}
function seedCatalog_(){const s=getSheet_(SHEETS.CATALOG);s.getRange(2,1,DEFAULT_CATALOG.length,H.CATALOG.length).setValues(DEFAULT_CATALOG.map(r=>r.concat([new Date()])));}
function seedBoot_(){const s=getSheet_(SHEETS.BOOT);if(s.getLastRow()>1)return;const a=[['BOOT-ACER','Acer','Laptop/PC','','F2','F12','Panduan awal; model dapat berbeda.'],['BOOT-ASUS','ASUS','Laptop/PC','','F2 atau Del','Esc','Panduan awal; model dapat berbeda.'],['BOOT-DELL','Dell','Laptop/PC','','F2','F12','Panduan awal; model dapat berbeda.'],['BOOT-HP','HP','Laptop/PC','','F10','F9','Startup Menu sering dibuka dengan Esc.'],['BOOT-LENOVO','Lenovo','Laptop/PC','','F1 atau F2','F12','Model tertentu memiliki tombol Novo.'],['BOOT-THINKPAD','ThinkPad','Laptop','','F1 atau F2','F12','Boot Menu umumnya F12.'],['BOOT-MSI','MSI','PC/Laptop','','Del atau F2','F11','Panduan awal; model dapat berbeda.'],['BOOT-GIGABYTE','Gigabyte','PC','','Del','F12','Panduan awal; model dapat berbeda.'],['BOOT-ASROCK','ASRock','PC','','Del atau F2','F11','Panduan awal; model dapat berbeda.']];s.getRange(2,1,a.length,H.BOOT.length).setValues(a.map(r=>r.concat([new Date()])));}
function seedNotes_(){const s=getSheet_(SHEETS.NOTES);if(s.getLastRow()>1)return;const a=[['NOTE-BOOT-001','Boot / Startup','Windows gagal boot','Pemeriksaan bertahap sebelum reinstall.','Nyalakan → amati startup → BIOS/Boot Menu bila diperlukan → boot media eksternal → cek storage internal → cek data → backup bila perlu → coba recovery → konsultasi sebelum reinstall.','Jangan menyimpulkan SSD rusak hanya karena Windows gagal boot.'],['NOTE-BACKUP-001','Backup Data','Backup sebelum instal ulang','Amankan data jika storage masih terbaca.','Identifikasi drive → cek Users → salin data yang disepakati → verifikasi → catat hasil → lanjut sesuai persetujuan.','Enkripsi/kerusakan storage dapat membatasi akses.'],['NOTE-RECOVERY-001','Windows Recovery','Repair your computer','Gunakan media recovery/installer yang sesuai.','Boot flashdisk → Repair your computer → Troubleshoot → opsi recovery yang relevan → restart → evaluasi.','Jangan hapus data tanpa persetujuan.'],['NOTE-SSD-001','Storage','Pemeriksaan SSD/HDD','Nilai deteksi dan indikator kesehatan storage.','Cek terdeteksi → partisi → SMART/health → error → simpulkan hati-hati.','SMART bukan jaminan drive pasti sehat.']];s.getRange(2,1,a.length,H.NOTES.length).setValues(a.map(r=>r.concat([new Date()])));}
function catalog_(){const s=getSheet_(SHEETS.CATALOG);if(s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,H.CATALOG.length).getValues().filter(r=>r[0]).map(catalogRow_);}
function catalogRow_(r){return{key:String(r[0]),name:String(r[1]),category:String(r[2]),min:Number(r[3]||0),base:Number(r[4]||0),max:Number(r[5]||0),fixed:String(r[6]).toUpperCase()==='YA',active:String(r[7]).toUpperCase()!=='TIDAK',description:String(r[8]||''),updatedAt:dt_(r[9]||new Date())};}
function noteRow_(r){return{id:String(r[0]),category:String(r[1]),title:String(r[2]),summary:String(r[3]),steps:String(r[4]),warnings:String(r[5]),updatedAt:dt_(r[6]||new Date())};}
function bootRow_(r){return{keyId:String(r[0]),brand:String(r[1]),type:String(r[2]),model:String(r[3]),bios:String(r[4]),boot:String(r[5]),notes:String(r[6]),updatedAt:dt_(r[7]||new Date())};}
function upsertRow_(s,width,id,index,row){const data=s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,width).getValues():[],i=data.findIndex(r=>String(r[index])===String(id));if(i<0)s.appendRow(row);else s.getRange(i+2,1,1,width).setValues([row]);}
function deleteByKey_(sheet,id,index,action){const s=getSheet_(sheet),data=s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).getValues():[],i=data.findIndex(r=>String(r[index])===String(id));if(i<0)throw err_('NOT_FOUND','Data tidak ditemukan.');s.deleteRow(i+2);writeAudit_(rid_(),'admin',action,String(id),'SUCCESS','Data dihapus.');}
function findOrderRow_(id){const s=getSheet_(SHEETS.ORDERS),last=s.getLastRow();if(last<2)return null;const ids=s.getRange(2,1,last-1,1).getDisplayValues().flat(),target=String(id||'').trim().toUpperCase();for(let i=0;i<ids.length;i++)if(String(ids[i]).trim().toUpperCase()===target)return{sheet:s,row:i+2,values:s.getRange(i+2,1,1,H.ORDERS.length).getValues()[0]};return null;}
function findOrder_(id){const f=findOrderRow_(id);return f?rowOrder_(f.values,f.row):null;}
function rowOrder_(r,row){return{rowNumber:row||'',id:String(r[0]),tanggal:dt_(r[1]),updatedAt:dt_(r[2]),nama:String(r[3]),email:String(r[4]),wa:String(r[5]),kategori:String(r[6]),layanan:String(r[7]),os:String(r[8]),metode:String(r[9]),brief:String(r[10]),tenggat:formatDate_(r[11]),status:String(r[12]||'Pending'),estimasi:Number(r[13]||0),payment:String(r[14]||'Belum Bayar'),revisi:Number(r[15]||0),link:String(r[16]||''),prioritas:String(r[17]||'Normal'),hariTersisa:r[18]===''?'':String(daysLeft_(r[11])),sumber:String(r[19]||''),catatan:String(r[21]||'')};}
function masked_(o){return{id:o.id,nama:mask_(o.nama),layanan:o.layanan,status:o.status,tenggat:o.tenggat,revisi:o.revisi};}
function verified_(o){return{id:o.id,nama:o.nama,email:o.email,wa:o.wa,kategori:o.kategori,layanan:o.layanan,os:o.os,metode:o.metode,brief:o.brief,tanggal:o.tanggal,tenggat:o.tenggat,status:o.status,estimasi:o.estimasi,payment:o.payment,revisi:o.revisi,prioritas:o.prioritas,hariTersisa:o.hariTersisa,link:o.link};}
function recentOrders_(s,n){const last=s.getLastRow();if(last<2)return[];const size=Math.min(Number(n)||APP.PAGE_SIZE,APP.MAX_PAGE_SIZE),start=Math.max(2,last-size+1);return s.getRange(start,1,last-start+1,H.ORDERS.length).getValues().reverse().filter(r=>r[0]).map((r,i)=>rowOrder_(r,last-i));}
function searchOrders_(s,q){const last=s.getLastRow();if(last<2)return[];const Q=normalize_(q),rows=s.getRange(2,1,last-1,H.ORDERS.length).getValues();return rows.map((r,i)=>{const id=normalize_(r[0]),name=normalize_(r[3]),email=normalize_(r[4]),wa=normalize_(r[5]),service=normalize_(r[7]),status=normalize_(r[12]);let score=0;if(id===Q)score+=1000;if(email===Q)score+=900;if(wa===Q)score+=850;if(name===Q)score+=800;if(id.indexOf(Q)===0)score+=650;if(name.indexOf(Q)!==-1)score+=500;if(service.indexOf(Q)!==-1)score+=350;if(status===Q)score+=100;return{r:r,score:score,row:i+2};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||b.row-a.row).slice(0,APP.MAX_PAGE_SIZE).map(x=>rowOrder_(x.r,x.row));}
function dashboardStats_(s){const z={total:0,pending:0,proses:0,review:0,selesai:0,dibatalkan:0,menungguBayar:0,lunas:0,terlambat:0,revenue:0};if(s.getLastRow()<2)return z;s.getRange(2,1,s.getLastRow()-1,H.ORDERS.length).getValues().forEach(r=>{if(!r[0])return;z.total++;const st=normalize_(r[12]),pay=normalize_(r[14]);if(st==='pending')z.pending++;if(st==='proses')z.proses++;if(st==='review')z.review++;if(st==='selesai')z.selesai++;if(st==='dibatalkan')z.dibatalkan++;if(pay==='belum bayar')z.menungguBayar++;if(pay==='lunas')z.lunas++;z.revenue+=Number(r[13]||0);if(daysLeft_(r[11])<0&&st!=='selesai'&&st!=='dibatalkan')z.terlambat++;});return z;}
function publicStats_(){const c=CacheService.getScriptCache(),x=c.get('ta:stats');if(x)return JSON.parse(x);const s=dashboardStats_(getSheet_(SHEETS.ORDERS)),r={totalPesanan:s.total,proses:s.proses,selesai:s.selesai};c.put('ta:stats',JSON.stringify(r),60);return r;}
function customerCount_(){const s=getSheet_(SHEETS.CUSTOMERS);return Math.max(0,s.getLastRow()-1);}
function upsertCustomer_(x,orderId,now){const s=getSheet_(SHEETS.CUSTOMERS),last=s.getLastRow(),email=normalize_(x.email);let row=0;if(last>=2){const a=s.getRange(2,5,last-1,1).getDisplayValues().flat();for(let i=0;i<a.length;i++)if(normalize_(a[i])===email){row=i+2;break;}}if(!row)s.appendRow(['CUS-'+hashShort_(email+'|'+Date.now()),now,now,safeCell_(x.nama),safeCell_(x.email),safeCell_(x.wa),1,orderId,'Aktif','']);else{s.getRange(row,3).setValue(now);s.getRange(row,4).setValue(safeCell_(x.nama));s.getRange(row,6).setValue(safeCell_(x.wa));s.getRange(row,7).setValue(Number(s.getRange(row,7).getValue()||0)+1);s.getRange(row,8).setValue(orderId);}}
function findRequest_(id){const s=getSheet_(SHEETS.REQUESTS);if(s.getLastRow()<2)return null;const q=clientId_(id),a=s.getRange(2,1,s.getLastRow()-1,4).getDisplayValues();for(let i=a.length-1;i>=0;i--)if(String(a[i][0])===q)return a[i][1];return null;}
function saveRequest_(crid,orderId,rid){getSheet_(SHEETS.REQUESTS).appendRow([safeCell_(crid),orderId,new Date(),hashShort_(crid+'|'+orderId+'|'+rid)]);}
function nextOrder_(s){const p=PropertiesService.getScriptProperties();let n=Number(p.getProperty('TA_ORDER_SEQ')||0);if(!n)n=maxOrder_(s);n++;p.setProperty('TA_ORDER_SEQ',String(n));return APP.ORDER_PREFIX+String(n).padStart(APP.ORDER_WIDTH,'0');}
function maxOrder_(s){if(s.getLastRow()<2)return 0;return s.getRange(2,1,s.getLastRow()-1,1).getDisplayValues().flat().reduce((m,v)=>{const x=String(v||'').match(/(\d+)/);return x?Math.max(m,Number(x[1])||0):m;},0);}
function writeAudit_(rid,a,action,entity,result,detail){try{getSheet_(SHEETS.AUDIT).appendRow([new Date(),safeCell_(rid),safeCell_(a),safeCell_(action),safeCell_(entity),safeCell_(result),safeCell_(detail)]);}catch(_){}}
function logErr_(rid,a,e,code){try{getSheet_(SHEETS.ERRORS).appendRow([new Date(),safeCell_(rid),safeCell_(a),safeCell_(code),safeCell_(e&&e.message?e.message:String(e)),safeCell_(e&&e.stack?e.stack:'')]);}catch(_){}}
function recentLogs_(sheet,n){const s=getSheet_(sheet);if(s.getLastRow()<2)return[];const last=s.getLastRow(),size=Math.min(Number(n)||50,100),start=Math.max(2,last-size+1);return s.getRange(start,1,last-start+1,s.getLastColumn()).getDisplayValues().reverse();}
function setting_(s,k,v,d){const last=s.getLastRow(),keys=last>1?s.getRange(2,1,last-1,1).getDisplayValues().flat():[],i=keys.indexOf(k);const row=i<0?s.getLastRow()+1:i+2;s.getRange(row,1,1,4).setValues([[k,safeCell_(v),safeCell_(d),new Date()]]);}
function param_(e,k){return e&&e.parameter?String(e.parameter[k]||''):'';}
function body_(e){const t=e&&e.postData&&e.postData.contents?String(e.postData.contents):'{}';if(t.length>APP.MAX_BODY_BYTES)throw err_('PAYLOAD_TOO_LARGE','Ukuran permintaan terlalu besar.');try{return JSON.parse(t);}catch(_){throw err_('INVALID_JSON','Data bukan JSON yang valid.');}}
function renderAdmin_(){return HtmlService.createTemplateFromFile('index').evaluate().setTitle('Tama Andrea Studio — Admin Console').addMetaTag('viewport','width=device-width, initial-scale=1').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function error_(c,m,rid,retry){return json_(errorObj_(c,m,rid,retry));}
function errorObj_(c,m,rid,retry){return{status:'error',code:c,message:m,requestId:rid,retryAfterSeconds:Number(retry||0)};}
function publicMsg_(e){return e&&e.code?String(e.message||'Permintaan tidak dapat diproses.'):'Server mengalami kendala. Silakan coba lagi.';}
function err_(c,m){const e=new Error(m);e.code=c;return e;}
function retryErr_(c,m,n){const e=err_(c,m);e.retryAfterSeconds=n;return e;}
function rid_(){return'REQ-'+Utilities.getUuid().replace(/-/g,'').slice(0,20).toUpperCase();}
function token_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');}
function hash_(v,s){let x=String(s)+'|'+String(v);for(let i=0;i<3000;i++)x=bytes_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,x,Utilities.Charset.UTF_8));return x;}
function hashShort_(v){return bytes_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8)).slice(0,24);}
function bytes_(a){return a.map(b=>{const n=b<0?b+256:b;return('0'+n.toString(16)).slice(-2);}).join('');}
function safeEq_(a,b){a=String(a);b=String(b);if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
function rate_(k,max,sec){const c=CacheService.getScriptCache(),key='ta:rl:'+hashShort_(k),now=Date.now(),raw=c.get(key);let s=raw?JSON.parse(raw):{n:0,reset:now+sec*1000};if(now>=s.reset)s={n:0,reset:now+sec*1000};if(s.n>=max)throw retryErr_('RATE_LIMITED','Terlalu banyak percobaan. Coba lagi setelah jeda.',Math.max(1,Math.ceil((s.reset-now)/1000)));s.n++;c.put(key,JSON.stringify(s),sec);}
function safe_(v,max){let t=String(v==null?'':v).replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim();return t.length>(max||5000)?t.slice(0,max||5000):t;}
function safeCell_(v){const t=safe_(v,5000);return/^[=+\-@]/.test(t)?"'"+t:t;}
function normalize_(v){return String(v==null?'':v).trim().toLowerCase().replace(/\s+/g,' ');}
function normalizeId_(v){return normalize_(String(v||'').normalize('NFKC'));}
function clientId_(v){const t=safe_(v,100);if(!t)return'';if(!/^[A-Za-z0-9._:-]{8,100}$/.test(t))throw err_('VALIDATION_ERROR','Client Request ID tidak valid.');return t;}
function orderId_(v){const t=String(v||'').trim().toUpperCase().replace(/^ORD[-\s]?/,'');const id=t?'ORD-'+t:'';return/^ORD-\d{1,12}$/.test(id)?id:'';}
function mask_(n){const p=String(n||'').trim().split(/\s+/);return p.map((x,i)=>i?x.charAt(0)+'***':x.slice(0,2)+'***').join(' ');}
function formatDate_(v){const d=v instanceof Date?v:new Date(v);return isNaN(d.getTime())?'':Utilities.formatDate(d,APP.TIMEZONE,'dd/MM/yyyy');}
function dt_(v){const d=v instanceof Date?v:new Date(v);return Utilities.formatDate(d,APP.TIMEZONE,'dd/MM/yyyy HH:mm:ss');}
function fmt_(v){return new Intl.NumberFormat('id-ID').format(Number(v)||0);}
function daysLeft_(v){if(!v)return'';const d=v instanceof Date?v:new Date(v);if(isNaN(d.getTime()))return'';const n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()),b=new Date(d.getFullYear(),d.getMonth(),d.getDate());return Math.ceil((b-a)/86400000);}
function addBusinessDays_(d,n){const x=new Date(d.getTime());while(n>0){x.setDate(x.getDate()+1);if(x.getDay()!==0&&x.getDay()!==6)n--;}return x;}
function parseDate_(v){const d=new Date(String(v||''));if(isNaN(d.getTime()))throw err_('VALIDATION_ERROR','Tanggal tidak valid.');return d;}
function enum_(v,a,label){const t=safe_(v,100);if(a.indexOf(t)<0)throw err_('VALIDATION_ERROR',label+' tidak valid.');return t;}
function int_(v,min,max,label){const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw err_('VALIDATION_ERROR',label+' tidak valid.');return n;}
function has_(o,k){return Object.prototype.hasOwnProperty.call(o,k);}
