/*
 * Tama Andrea Studio — Backend Core
 * V6.0 — Sheets API, public order flow, masked tracking and verified customer access.
 * Admin secrets/authentication remain in admin-security.gs. Never commit secrets here.
 */
const APP=Object.freeze({VERSION:'6.0.0',TIMEZONE:'Asia/Jakarta',CURRENCY:'IDR',ORDER_PREFIX:'ORD-',ORDER_WIDTH:4,MAX_BODY_BYTES:30000,PAGE_SIZE:20,MAX_PAGE_SIZE:50,PUBLIC_TRACK_LIMIT:12,PUBLIC_TRACK_WINDOW:600,PUBLIC_ORDER_LIMIT:8,PUBLIC_ORDER_WINDOW:600,VERIFY_LIMIT:5,VERIFY_WINDOW:600,VERIFIED_TOKEN_SECONDS:900,STATUS:['Pending','Proses','Review','Selesai','Dibatalkan'],PAYMENT:['Belum Bayar','DP','Lunas','Dibatalkan'],PRIORITY:['Rendah','Normal','Menengah','Tinggi'],OS:['Windows 11 Home','Windows 11 Pro','Windows 11 Enterprise LTSC 2024','Ubuntu','Debian','Kali Linux'],METHOD:['Teknisi datang ke lokasi — Sabtu/Minggu','Saya membawa perangkat — bisa diantar setelah konfirmasi, termasuk malam hari']});
const SHEETS=Object.freeze({ORDERS:'Orders',CUSTOMERS:'Customers',AUDIT:'Audit_Log',ERRORS:'Error_Log',REQUESTS:'Request_Index',SETTINGS:'Settings',SERVICE_NOTES:'Service_Notes',BOOT_KEYS:'Boot_Keys'});
const ORDER_HEADERS=['ID Pesanan','Tanggal Masuk','Tanggal Update','Nama Lengkap','Alamat Email','Kontak/WA','Kategori Layanan','Layanan Dipilih','Pilihan OS','Metode Layanan','Rincian Brief','Tenggat Waktu','Status','Estimasi Biaya','Status Pembayaran','Jumlah Revisi','Link Hasil','Prioritas Deadline','Hari Tersisa','Sumber','Client Request ID','Catatan Internal'];
const CUSTOMER_HEADERS=['Customer ID','Pertama Masuk','Terakhir Masuk','Nama','Email','Kontak/WA','Jumlah Pesanan','Order Terakhir','Status Customer','Catatan'];
const AUDIT_HEADERS=['Timestamp','Request ID','Actor','Action','Entity ID','Result','Detail'];
const ERROR_HEADERS=['Timestamp','Request ID','Action','Code','Message','Stack'];
const REQUEST_HEADERS=['Client Request ID','Order ID','Created At','Request Hash'];
const SETTINGS_HEADERS=['Key','Value','Description','Updated At'];
const SERVICE_CATALOG=Object.freeze({
'Poster & Flyer Digital':{base:15000,min:15000,max:80000,group:'design'},'Banner Marketplace':{base:20000,min:20000,max:80000,group:'design'},'Konten Media Sosial':{base:20000,min:20000,max:85000,group:'design'},'Logo Profesional':{base:20000,min:20000,max:90000,group:'design'},'Desain Presentasi':{base:20000,min:20000,max:85000,group:'design'},'Edit Foto Produk':{base:20000,min:20000,max:80000,group:'design'},'Paket OS Basic - Rp90.000':{base:90000,min:90000,max:90000,group:'it'},'Paket OS + Office - Rp125.000':{base:125000,min:125000,max:125000,group:'it'},'Paket OS + Backup - Rp135.000':{base:135000,min:135000,max:135000,group:'it'},'Paket OS + Office + Backup - Rp160.000':{base:160000,min:160000,max:160000,group:'it'},'Diagnosis PC / laptop - Rp35.000':{base:35000,min:35000,max:35000,group:'it-diagnosis'},'Cek kesehatan SSD/HDD - Rp35.000':{base:35000,min:35000,max:35000,group:'it-add-on'},'Backup data sebelum instal ulang - mulai Rp40.000':{base:40000,min:40000,max:100000,group:'it-add-on'},'Driver & update dasar - mulai Rp25.000':{base:25000,min:25000,max:40000,group:'it-add-on'},'Cek kompatibilitas komponen & rekomendasi upgrade':{base:25000,min:25000,max:75000,group:'it-upgrade'},'Pasang / Upgrade RAM - Rp50.000':{base:50000,min:50000,max:50000,group:'it-install'},'Pasang SSD / HDD - Rp50.000':{base:50000,min:50000,max:50000,group:'it-install'},'Pasang CPU - Rp60.000':{base:60000,min:60000,max:60000,group:'it-install'},'Pasang GPU - Rp60.000':{base:60000,min:60000,max:60000,group:'it-install'},'Pasang PSU - Rp60.000':{base:60000,min:60000,max:60000,group:'it-install'},'Pasang / Upgrade 2 Komponen - Rp90.000':{base:90000,min:90000,max:90000,group:'it-install'},'Instal Microsoft Office - Rp35000':{base:35000,min:35000,max:35000,group:'it-software'},'Restore / Flash iPhone - mulai Rp60.000':{base:60000,min:60000,max:100000,group:'it-device'},'Bantuan Find Hub Android - mulai Rp35.000':{base:35000,min:35000,max:75000,group:'it-device'},'Bantuan Find My / Lacak iPhone - mulai Rp35.000':{base:35000,min:35000,max:75000,group:'it-device'}});
function onOpen(){SpreadsheetApp.getUi().createMenu('TA Backend').addItem('Setup / Periksa Backend','setupBackend').addItem('Konfigurasi Admin','configureAdminSecurity').addItem('Health Check','runHealthCheck').addToUi()}
function doGet(e){const rid=makeRequestId_();try{const a=getParam_(e,'action');if(a==='ping')return jsonResponse_({status:'ok',service:'tama-andrea-studio-backend',version:APP.VERSION,requestId:rid,time:nowIso_()});if(a==='stats')return jsonResponse_({status:'ok',requestId:rid,data:getPublicStats_(),updatedAt:formatDateTime_(new Date())});if(a==='track'){enforcePublicTrackRateLimit_(getParam_(e,'id'));const id=normalizeOrderId_(getParam_(e,'id'));if(!id)return errorResponse_('VALIDATION_ERROR','ID pesanan tidak valid.',rid);const o=findOrderById_(id);if(!o)return errorResponse_('NOT_FOUND','Pesanan tidak ditemukan.',rid);return jsonResponse_({status:'ok',requestId:rid,order:publicOrder_(o)});}if(a==='admin')return renderAdmin_();return jsonResponse_({status:'ok',service:'Tama Andrea Studio',version:APP.VERSION,requestId:rid,endpoints:['ping','stats','track','newOrder','verifyOrder','getVerifiedOrder']})}catch(err){logError_(rid,'GET',err.code||'INTERNAL_ERROR',err);return errorResponse_(err.code||'INTERNAL_ERROR',publicErrorMessage_(err),rid)}}
function doPost(e){const rid=makeRequestId_();let action='unknown';try{const b=readPostBody_(e);action=String(b.action||'').trim();if(!action)return errorResponse_('VALIDATION_ERROR','Action tidak ditemukan.',rid);if(action==='newOrder'){const d=b.data||b,crid=normalizeClientRequestId_(b.clientRequestId||d.clientRequestId||'');enforceRateLimit_('public-order',APP.PUBLIC_ORDER_LIMIT,APP.PUBLIC_ORDER_WINDOW);return jsonResponse_(createNewOrderRecord_(d,{requestId:rid,clientRequestId:crid,source:'website'}))}if(action==='verifyOrder'){const id=b.id||b.orderId||'';enforceRateLimit_('verify:'+hashShort_(id),APP.VERIFY_LIMIT,APP.VERIFY_WINDOW);return jsonResponse_(verifyOrder_(id,b.name||'',b.email||'',rid))}if(action==='getVerifiedOrder')return jsonResponse_(getVerifiedOrder_(b.id||b.orderId||'',b.verificationToken||'',rid));return errorResponse_('UNKNOWN_ACTION','Action tidak dikenali.',rid)}catch(err){logError_(rid,action,err.code||'INTERNAL_ERROR',err);return errorResponse_(err.code||'INTERNAL_ERROR',publicErrorMessage_(err),rid)}}
function setupBackend(){const ss=getSpreadsheet_();[[SHEETS.ORDERS,ORDER_HEADERS],[SHEETS.CUSTOMERS,CUSTOMER_HEADERS],[SHEETS.AUDIT,AUDIT_HEADERS],[SHEETS.ERRORS,ERROR_HEADERS],[SHEETS.REQUESTS,REQUEST_HEADERS],[SHEETS.SETTINGS,SETTINGS_HEADERS],[SHEETS.SERVICE_NOTES,['Note ID','Kategori','Judul','Ringkasan','Langkah Kerja','Peringatan / Batasan','Updated At']],[SHEETS.BOOT_KEYS,['Brand','Jenis Perangkat','Model / Motherboard','BIOS / UEFI','Boot Menu','Catatan','Updated At']]].forEach(function(d){configureSheet_(getOrCreateSheet_(ss,d[0],d[1]),d[1])});const p=PropertiesService.getScriptProperties(),orders=ss.getSheetByName(SHEETS.ORDERS);if(!p.getProperty('TA_ORDER_SEQ'))p.setProperty('TA_ORDER_SEQ',String(findMaxOrderNumber_(orders)));const s=ss.getSheetByName(SHEETS.SETTINGS);writeSetting_(s,'BACKEND_VERSION',APP.VERSION,'Versi backend aktif.');writeSetting_(s,'PUBLIC_TRACKING','MASKED_UNTIL_VERIFIED','Data pelanggan tersamar sebelum verifikasi.');writeSetting_(s,'PUBLIC_CUSTOMER_ACCESS','DENIED','Sheet Customers tidak pernah diekspos ke API publik.');writeSetting_(s,'ADMIN_AUTH','3_LAYER','Gerbang → kode akses → identitas/password.');writeSetting_(s,'HOME_VISIT','SATURDAY_SUNDAY','Kunjungan teknisi hanya Sabtu/Minggu.');writeSetting_(s,'ORDER_SEARCH','WEIGHTED_SERVER_SIDE','Pencarian admin memakai beberapa field dan prioritas kecocokan.');writeSetting_(s,'PRICING_ENGINE','RULE_BASED','Estimasi memakai katalog + kualitas brief + kompleksitas + urgensi.');SpreadsheetApp.flush();return{status:'success',version:APP.VERSION,sheets:Object.keys(SHEETS).map(function(k){return SHEETS[k]}),orderSequence:Number(p.getProperty('TA_ORDER_SEQ')||0)}}
function runHealthCheck(){const r={status:'ok',version:APP.VERSION,time:nowIso_(),spreadsheet:'',sheets:{},config:{}};try{const ss=getSpreadsheet_();r.spreadsheet=ss.getName();Object.keys(SHEETS).forEach(function(k){const n=SHEETS[k],s=ss.getSheetByName(n);r.sheets[n]=!!s&&s.getLastColumn()>=1});const p=PropertiesService.getScriptProperties();r.config.orderSequence=Number(p.getProperty('TA_ORDER_SEQ')||0);r.config.adminConfigured=!!p.getProperty('TA_ADMIN_GATE_HASH')&&!!p.getProperty('TA_ADMIN_CODE_HASH');r.config.spreadsheetBound=!!p.getProperty('TA_SPREADSHEET_ID')||!!SpreadsheetApp.getActiveSpreadsheet();r.config.publicDataIsolation=true;r.status=Object.keys(r.sheets).every(function(n){return r.sheets[n]})?'ok':'warning';return r}catch(err){r.status='error';r.error='Health check gagal.';logError_(makeRequestId_(),'runHealthCheck','HEALTH_CHECK_FAILED',err);return r}}
function getDashboardData(searchTerm,token){requireAdmin_(token);const s=getOrdersSheet_(),q=sanitizePlain_(searchTerm,120),orders=q?searchOrders_(s,q):recentOrders_(s,APP.PAGE_SIZE);return{status:'ok',version:APP.VERSION,stats:dashboardStats_(s),orders:orders,sheetName:s.getName(),updatedAt:formatDateTime_(new Date())}}
function saveOrderFromConsole(data,token){requireAdmin_(token);return createNewOrderRecord_(data||{},{requestId:makeRequestId_(),clientRequestId:'admin-'+makeToken_(),source:'admin'})}
function updateOrderFromConsole(id,patch,token){requireAdmin_(token);const normalizedId=normalizeOrderId_(id);if(!normalizedId)throw appError_('VALIDATION_ERROR','ID pesanan tidak valid.');const found=findOrderRow_(normalizedId);if(!found)throw appError_('NOT_FOUND','Pesanan tidak ditemukan.');const p=patch||{},row=found.values.slice();if(hasOwn_(p,'status'))row[12]=validateEnum_(p.status,APP.STATUS,'Status');if(hasOwn_(p,'statusPembayaran'))row[14]=validateEnum_(p.statusPembayaran,APP.PAYMENT,'Status pembayaran');if(hasOwn_(p,'payment'))row[14]=validateEnum_(p.payment,APP.PAYMENT,'Status pembayaran');if(hasOwn_(p,'jumlahRevisi'))row[15]=clampInt_(p.jumlahRevisi,0,99,'Jumlah revisi');if(hasOwn_(p,'revisi'))row[15]=clampInt_(p.revisi,0,99,'Jumlah revisi');if(hasOwn_(p,'prioritas'))row[17]=validateEnum_(p.prioritas,APP.PRIORITY,'Prioritas');if(hasOwn_(p,'priority'))row[17]=validateEnum_(p.priority,APP.PRIORITY,'Prioritas');if(hasOwn_(p,'link'))row[16]=safeCell_(String(p.link||'').slice(0,500));if(hasOwn_(p,'catatan'))row[21]=safeCell_(String(p.catatan||'').slice(0,1500));if(hasOwn_(p,'note'))row[21]=safeCell_(String(p.note||'').slice(0,1500));if(hasOwn_(p,'tenggat'))row[11]=parseDateInput_(p.tenggat,'Tenggat');row[2]=new Date();row[18]=computeDaysLeft_(row[11]);found.sheet.getRange(found.row,1,1,ORDER_HEADERS.length).setValues([row]);writeAudit_(makeRequestId_(),'admin','UPDATE_ORDER',normalizedId,'SUCCESS','Order diperbarui.');return{status:'ok',order:rowToOrder_(row,found.row)}}
function deleteOrderFromConsole(id,token){requireAdmin_(token);const normalizedId=normalizeOrderId_(id);const found=findOrderRow_(normalizedId);if(!found)throw appError_('NOT_FOUND','Pesanan tidak ditemukan.');found.sheet.deleteRow(found.row);writeAudit_(makeRequestId_(),'admin','DELETE_ORDER',normalizedId,'SUCCESS','Order dihapus.');return{status:'ok',id:normalizedId}}
function analyzeBriefFromConsole(service,brief,token){requireAdmin_(token);return analyzeOrder_(service,brief,'')}
function createNewOrderRecord_(params,meta){const requestId=meta.requestId||makeRequestId_(),input=normalizeOrderInput_(params||{});validatePayloadSize_(input);if(meta.clientRequestId)input.clientRequestId=normalizeClientRequestId_(meta.clientRequestId);if(input.clientRequestId){const old=findRequest_(input.clientRequestId);if(old){const ex=findOrderById_(old);return{status:'ok',duplicate:true,id:old,orderId:old,requestId:requestId,estimate:ex?ex.estimasi:0,deadline:ex?ex.tenggat:'',priority:ex?ex.prioritas:'Normal',days:ex?Number(ex.hariTersisa||0):0}}}const analysis=analyzeOrder_(input.layanan,input.brief,input.os),lock=LockService.getScriptLock();lock.waitLock(10000);try{const sheet=getOrdersSheet_(),orderId=nextOrderId_(sheet),now=new Date(),due=addBusinessDays_(now,analysis.days),row=new Array(ORDER_HEADERS.length).fill('');row[0]=orderId;row[1]=now;row[2]=now;row[3]=safeCell_(input.nama);row[4]=safeCell_(input.email);row[5]=safeCell_(input.wa);row[6]=safeCell_(input.kategori);row[7]=safeCell_(input.layanan);row[8]=safeCell_(input.os);row[9]=safeCell_(input.metode);row[10]=safeCell_(input.brief);row[11]=due;row[12]='Pending';row[13]=analysis.estimate;row[14]='Belum Bayar';row[15]=0;row[17]=analysis.priority;row[18]=analysis.days;row[19]=safeCell_(meta.source||'website');row[20]=safeCell_(input.clientRequestId);row[21]=safeCell_('Analyzer: '+analysis.summary+' | Risiko: '+(analysis.risks.join(', ')||'none'));const rn=sheet.getLastRow()+1;sheet.getRange(rn,1,1,ORDER_HEADERS.length).setValues([row]);sheet.getRange(rn,2,1,2).setNumberFormat('dd/MM/yyyy HH:mm');sheet.getRange(rn,12).setNumberFormat('dd/MM/yyyy');sheet.getRange(rn,14).setNumberFormat('#,##0');upsertCustomer_(input,orderId,now);if(input.clientRequestId)saveRequest_(input.clientRequestId,orderId,requestId);writeAudit_(requestId,meta.source==='admin'?'admin':'public','CREATE_ORDER',orderId,'SUCCESS','Order dibuat.');return{status:'ok',id:orderId,orderId:orderId,requestId:requestId,layanan:input.layanan,estimate:'Rp '+formatRupiah_(analysis.estimate),estimatePrice:analysis.estimate,estimateMin:analysis.min,estimateMax:analysis.max,deadline:formatDate_(due),priority:analysis.priority,days:analysis.days,analysis:{quality:analysis.quality,difficulty:analysis.difficulty,riskFlags:analysis.risks,summary:analysis.summary}}}finally{lock.releaseLock()}}
function normalizeOrderInput_(p){const nama=sanitizePlain_(p.Nama||p['Nama Lengkap']||p.nama||'',80),email=normalizeEmail_(p.Email||p['Alamat Email']||''),wa=String(p.WA||p.WhatsApp||p['Kontak/WA']||p['No. WhatsApp']||'').replace(/[^\d+]/g,''),kategori=sanitizePlain_(p.Kategori||p['Kategori Layanan']||p['Jenis Desain']||'',50),layanan=sanitizePlain_(p.Layanan||p['Layanan Dipilih']||p.service||'',1000),os=sanitizePlain_(p.OS||p['Pilihan OS']||'',80),metode=sanitizePlain_(p.Metode||p['Metode Layanan']||'',180),brief=sanitizePlain_(p.Brief||p['Rincian Brief']||p['Keterangan Proyek']||'',5000);if(nama.length<2)throw appError_('VALIDATION_ERROR','Nama minimal 2 karakter.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw appError_('VALIDATION_ERROR','Format email tidak valid.');if(wa&&!/^\+?\d{8,15}$/.test(wa))throw appError_('VALIDATION_ERROR','Nomor WhatsApp tidak valid.');if(kategori&&!/Desain|Servis/i.test(kategori))throw appError_('VALIDATION_ERROR','Kategori layanan tidak dikenali.');if(layanan.length<2)throw appError_('VALIDATION_ERROR','Layanan belum dipilih.');if(brief.length<5)throw appError_('VALIDATION_ERROR','Keterangan kebutuhan terlalu singkat.');if(os&&APP.OS.indexOf(os)===-1)throw appError_('VALIDATION_ERROR','Pilihan OS tidak dikenali.');if(metode&&APP.METHOD.indexOf(metode)===-1)throw appError_('VALIDATION_ERROR','Metode layanan tidak dikenali.');if(/desain/i.test(kategori)&&/(Paket OS|Diagnosis PC|SSD\/HDD|Pasang|Restore \/ Flash iPhone|Find Hub|Find My|Microsoft Office|Driver & update|Kompatibilitas)/i.test(layanan))throw appError_('VALIDATION_ERROR','Layanan IT tidak cocok dengan kategori desain.');if(/servis/i.test(kategori)&&/(Poster|Banner|Logo|Presentasi|Media Sosial|Foto Produk)/i.test(layanan))throw appError_('VALIDATION_ERROR','Layanan desain tidak cocok dengan kategori servis IT.');if(/Android/i.test(layanan)&&/coming soon/i.test(layanan))throw appError_('VALIDATION_ERROR','Layanan Android belum tersedia.');return{nama:nama,email:email,wa:wa,kategori:kategori,layanan:layanan,os:os,metode:metode,brief:brief,clientRequestId:''}}
function analyzeOrder_(layanan,briefText,os){const serviceString=String(layanan||''),brief=String(briefText||'').trim().toLowerCase(),selected=splitServices_(serviceString);let base=0,minPrice=0,maxPrice=0,known=0;const groups={};selected.forEach(function(item){const key=findCatalogKey_(item);if(key){const c=SERVICE_CATALOG[key];base+=c.base;minPrice+=c.min;maxPrice+=c.max;groups[c.group]=(groups[c.group]||0)+1;known++}else{base+=25000;minPrice+=25000;maxPrice+=50000}});if(!base){base=/servis|OS|Windows|Ubuntu|Debian|Kali|RAM|CPU|GPU|PSU|SSD|HDD|iPhone/i.test(serviceString)?90000:20000;minPrice=base;maxPrice=base}const urgent=/(urgent|besok|segera|buru|mendesak|hari ini|malam ini)/i.test(brief),complex=/(3d|animasi|manipulasi|detail|banyak halaman|banyak konsep|multi|branding lengkap|revisi banyak|kompleks|custom)/i.test(brief),light=/(sederhana|simple|simpel|ringan|satu halaman|satu desain)/i.test(brief),quality=calculateBriefQuality_(briefText),itWork=Object.keys(groups).some(function(g){return g.indexOf('it')===0});let multiplier=1,priority='Normal',days=itWork?2:3;const risks=[];if(urgent){multiplier*=1.10;priority='Tinggi';days=Math.max(1,days-1);risks.push('deadline-mendesak')}if(complex){multiplier*=1.15;if(priority!=='Tinggi')priority='Menengah';days+=2;risks.push('brief-kompleks')}if(light&&!urgent&&!complex){multiplier*=0.95;priority='Rendah';days=Math.max(1,days-1)}if(quality<50)risks.push('brief-perlu-diperjelas');if(known<selected.length)risks.push('layanan-tidak-dikenal');if(!os&&/(install|instalasi|OS|Windows|Ubuntu|Debian|Kali)/i.test(serviceString))risks.push('OS-belum-dipilih');const fixed=selected.length===1&&known===1&&minPrice===maxPrice,estimate=fixed?minPrice:roundToThousand_(base*multiplier),min=fixed?minPrice:roundToThousand_(minPrice*multiplier),max=fixed?maxPrice:roundToThousand_(maxPrice*multiplier);return{estimate:estimate,min:min,max:max,priority:priority,days:Math.max(1,Math.min(7,days)),difficulty:complex?'Kompleks':(light?'Ringan':(itWork?'Teknis':'Normal')),quality:quality,risks:risks,summary:['base='+base,'multiplier='+multiplier.toFixed(2),'quality='+quality,'known='+known+'/'+selected.length,'fixed='+fixed].join(', ')}}
function calculateBriefQuality_(brief){const text=String(brief||'').trim();if(!text)return 0;let score=20;if(text.length>=30)score+=15;if(text.length>=80)score+=15;if(text.length>=160)score+=10;if(/(ukuran|size|dimensi|px|cm|mm)/i.test(text))score+=10;if(/(deadline|tenggat|tanggal|besok|hari)/i.test(text))score+=10;if(/(referensi|contoh|warna|brand|target|tujuan)/i.test(text))score+=15;if(/(format|png|jpg|pdf|pptx|ai|psd|svg)/i.test(text))score+=5;return Math.min(100,score)}
function verifyOrder_(id,name,email,requestId){const normalizedId=normalizeOrderId_(id);if(!normalizedId)return errorObject_('VALIDATION_ERROR','ID pesanan tidak valid.',requestId);const order=findOrderById_(normalizedId);if(!order)return errorObject_('NOT_FOUND','Pesanan tidak ditemukan.',requestId);const n=normalizeIdentity_(name),e=normalizeEmail_(email);if(!n||!e)return errorObject_('VALIDATION_ERROR','Nama dan email wajib diisi.',requestId);if(normalizeIdentity_(order.nama)!==n||normalizeEmail_(order.email)!==e){writeAudit_(requestId,'public','VERIFY_ORDER',normalizedId,'DENIED','Nama/email tidak cocok.');return errorObject_('VERIFICATION_FAILED','Nama atau email tidak cocok dengan data pesanan.',requestId)}const token=makeToken_();CacheService.getScriptCache().put('verified-order:'+token,JSON.stringify({id:normalizedId,createdAt:Date.now()}),APP.VERIFIED_TOKEN_SECONDS);writeAudit_(requestId,'public','VERIFY_ORDER',normalizedId,'SUCCESS','Pemilik pesanan terverifikasi.');return{status:'ok',requestId:requestId,verificationToken:token,expiresIn:APP.VERIFIED_TOKEN_SECONDS,order:verifiedOrder_(order)}}
function getVerifiedOrder_(id,token,requestId){const normalizedId=normalizeOrderId_(id),raw=String(token||'').trim();if(!normalizedId||!raw)return errorObject_('VALIDATION_ERROR','ID dan token verifikasi diperlukan.',requestId);const payload=CacheService.getScriptCache().get('verified-order:'+raw);if(!payload)return errorObject_('VERIFICATION_EXPIRED','Verifikasi sudah kedaluwarsa. Silakan ulangi verifikasi.',requestId);const parsed=JSON.parse(payload);if(parsed.id!==normalizedId)return errorObject_('VERIFICATION_FAILED','Token verifikasi tidak sesuai.',requestId);const order=findOrderById_(normalizedId);if(!order)return errorObject_('NOT_FOUND','Pesanan tidak ditemukan.',requestId);return{status:'ok',requestId:requestId,order:verifiedOrder_(order)}}
function verifiedOrder_(o){return{id:o.id,tanggal:o.tanggalMasuk,nama:o.nama,email:o.email,wa:o.wa,kategori:o.kategori,layanan:o.layanan,os:o.os,metode:o.metode,brief:o.brief,tenggat:o.tenggat,status:o.status,estimasi:o.estimatePrice,payment:o.statusPembayaran,revisi:o.revisi,link:o.link,prioritas:o.prioritas,hariTersisa:o.hariTersisa}}
function publicOrder_(o){return{id:o.id,nama:maskName_(o.nama),layanan:o.layanan,status:o.status,tenggat:o.tenggat,prioritas:o.prioritas}}
function getPublicStats_(){const c=CacheService.getScriptCache(),key='ta:public:stats',cached=c.get(key);if(cached)return JSON.parse(cached);const s=dashboardStats_(getOrdersSheet_()),r={totalPesanan:s.totalPesanan,selesai:s.selesai};c.put(key,JSON.stringify(r),60);return r}
function dashboardStats_(sheet){const s={totalPesanan:0,pending:0,proses:0,review:0,selesai:0,dibatalkan:0,terlambat:0,estimasiRevenue:0,bulanIni:0,menungguDp:0,lunas:0,revisiAktif:0},last=sheet.getLastRow();if(last<2)return s;const rows=sheet.getRange(2,1,last-1,ORDER_HEADERS.length).getValues(),month=Utilities.formatDate(new Date(),APP.TIMEZONE,'yyyy-MM');rows.forEach(function(r){if(!r[0])return;s.totalPesanan++;const st=normalizeSearch_(r[12]),pay=normalizeSearch_(r[14]);if(st==='pending')s.pending++;else if(st==='proses')s.proses++;else if(st==='review')s.review++;else if(st==='selesai')s.selesai++;else if(st==='dibatalkan')s.dibatalkan++;if(pay==='belum bayar')s.menungguDp++;if(pay==='lunas')s.lunas++;s.estimasiRevenue+=parseNumber_(r[13]);s.revisiAktif+=parseNumber_(r[15]);const d=r[1] instanceof Date?r[1]:new Date(r[1]);if(!isNaN(d.getTime())&&Utilities.formatDate(d,APP.TIMEZONE,'yyyy-MM')===month)s.bulanIni++;const left=computeDaysLeft_(r[11]);if(left!==''&&left<0&&st!=='selesai'&&st!=='dibatalkan')s.terlambat++});return s}
function searchOrders_(sheet,term){const q=normalizeSearch_(term);if(!q)return recentOrders_(sheet,APP.PAGE_SIZE);const last=sheet.getLastRow();if(last<2)return [];const rows=sheet.getRange(2,1,last-1,ORDER_HEADERS.length).getValues(),scored=[];rows.forEach(function(r,i){if(!r[0])return;const id=normalizeSearch_(r[0]),name=normalizeSearch_(r[3]),email=normalizeSearch_(r[4]),wa=normalizeSearch_(r[5]),cat=normalizeSearch_(r[6]),service=normalizeSearch_(r[7]),os=normalizeSearch_(r[8]),status=normalizeSearch_(r[12]),hay=[id,name,email,wa,cat,service,os,status].join(' ');if(hay.indexOf(q)===-1)return;let score=1;if(id===q)score+=100;else if(id.indexOf(q)===0)score+=50;if(email===q)score+=80;else if(email.indexOf(q)===0)score+=35;if(name===q)score+=60;else if(name.indexOf(q)===0)score+=30;if(wa===q)score+=70;if(service.indexOf(q)!==-1)score+=15;if(status===q)score+=10;scored.push({row:r,score:score,index:i})});scored.sort(function(a,b){return b.score-a.score||b.index-a.index});return scored.slice(0,APP.MAX_PAGE_SIZE).map(function(x){return rowToOrder_(x.row,x.index+2)})}
function recentOrders_(sheet,limit){const last=sheet.getLastRow();if(last<2)return [];const n=Math.min(Number(limit)||APP.PAGE_SIZE,APP.MAX_PAGE_SIZE),start=Math.max(2,last-n+1),rows=sheet.getRange(start,1,last-start+1,ORDER_HEADERS.length).getValues().reverse();return rows.filter(function(r){return r[0]}).map(function(r,i){return rowToOrder_(r,last-i)})}
function rowToOrder_(r,rowNumber){const pay=valueString_(r[14])||'Belum Bayar';return{row:rowNumber||'',id:valueString_(r[0]),tanggalMasuk:formatDateTimeValue_(r[1]),tanggalUpdate:formatDateTimeValue_(r[2]),nama:valueString_(r[3]),email:valueString_(r[4]),wa:valueString_(r[5]),kategori:valueString_(r[6]),layanan:valueString_(r[7]),os:valueString_(r[8]),metode:valueString_(r[9]),brief:valueString_(r[10]),tenggat:formatDateValue_(r[11]),status:valueString_(r[12])||'Pending',biaya:r[13]===''?'':'Rp '+formatRupiah_(r[13]),estimasi:r[13]===''?0:parseNumber_(r[13]),estimatePrice:parseNumber_(r[13]),statusPembayaran:pay,payment:pay,revisi:r[15]===''?'0':String(r[15]),link:valueString_(r[16]),prioritas:valueString_(r[17])||'Normal',hariTersisa:r[18]===''?'':String(computeDaysLeft_(r[11])),sumber:valueString_(r[19]),clientRequestId:valueString_(r[20]),catatan:valueString_(r[21])}}
function findOrderRow_(id){const sheet=getOrdersSheet_(),last=sheet.getLastRow(),target=String(id||'').trim().toUpperCase();if(last<2)return null;const ids=sheet.getRange(2,1,last-1,1).getDisplayValues().flat();for(let i=0;i<ids.length;i++)if(String(ids[i]||'').trim().toUpperCase()===target)return{sheet:sheet,row:i+2,values:sheet.getRange(i+2,1,1,ORDER_HEADERS.length).getValues()[0],id:target};return null}
function findOrderById_(id){const f=findOrderRow_(id);return f?rowToOrder_(f.values,f.row):null}
function getOrdersSheet_(){const ss=getSpreadsheet_();let sheet=ss.getSheetByName(SHEETS.ORDERS);if(!sheet){setupBackend();sheet=ss.getSheetByName(SHEETS.ORDERS)}if(!sheet)throw new Error('Sheet Orders tidak ditemukan.');return sheet}
function getSpreadsheet_(){const p=PropertiesService.getScriptProperties(),id=String(p.getProperty('TA_SPREADSHEET_ID')||'').trim();if(id){try{return SpreadsheetApp.openById(id)}catch(_){throw new Error('Spreadsheet ID pada Script Properties tidak dapat dibuka.')}}const active=SpreadsheetApp.getActiveSpreadsheet();if(!active)throw new Error('Spreadsheet aktif tidak ditemukan.');return active}
function getOrCreateSheet_(ss,name,headers){let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);ensureHeaders_(s,headers);return s}
function configureSheet_(s,h){ensureHeaders_(s,h);s.setFrozenRows(1);try{s.getRange(1,1,1,h.length).setFontWeight('bold')}catch(_){} }
function ensureHeaders_(s,h){if(s.getLastRow()===0){s.getRange(1,1,1,h.length).setValues([h]);return}const ex=s.getRange(1,1,1,Math.max(h.length,s.getLastColumn())).getDisplayValues()[0];for(let i=0;i<h.length;i++)if(normalizeSearch_(ex[i])!==normalizeSearch_(h[i]))s.getRange(1,i+1).setValue(h[i])}
function nextOrderId_(sheet){const p=PropertiesService.getScriptProperties();let seq=Number(p.getProperty('TA_ORDER_SEQ')||0);if(!seq)seq=findMaxOrderNumber_(sheet);seq++;p.setProperty('TA_ORDER_SEQ',String(seq));return APP.ORDER_PREFIX+String(seq).padStart(APP.ORDER_WIDTH,'0')}
function findMaxOrderNumber_(sheet){const last=sheet.getLastRow();if(last<2)return 0;return sheet.getRange(2,1,last-1,1).getDisplayValues().flat().reduce(function(m,v){const x=String(v||'').match(/(\d+)/);return x?Math.max(m,Number(x[1])||0):m},0)}
function upsertCustomer_(input,orderId,now){const sheet=getSpreadsheet_().getSheetByName(SHEETS.CUSTOMERS);if(!sheet)return;const last=sheet.getLastRow(),email=normalizeEmail_(input.email);let row=0;if(last>=2){const values=sheet.getRange(2,5,last-1,1).getDisplayValues().flat();for(let i=0;i<values.length;i++)if(normalizeEmail_(values[i])===email){row=i+2;break}}if(!row){sheet.appendRow(['CUS-'+hashShort_(email+'|'+Date.now()).toUpperCase(),now,now,safeCell_(input.nama),safeCell_(input.email),safeCell_(input.wa),1,orderId,'Aktif','']);return}const count=parseNumber_(sheet.getRange(row,7).getValue())+1;sheet.getRange(row,3).setValue(now);sheet.getRange(row,4).setValue(safeCell_(input.nama));sheet.getRange(row,6).setValue(safeCell_(input.wa));sheet.getRange(row,7).setValue(count);sheet.getRange(row,8).setValue(orderId)}
function findRequest_(clientRequestId){const sheet=getSpreadsheet_().getSheetByName(SHEETS.REQUESTS);if(!sheet||sheet.getLastRow()<2)return null;const target=normalizeClientRequestId_(clientRequestId),rows=sheet.getRange(2,1,sheet.getLastRow()-1,4).getDisplayValues();for(let i=rows.length-1;i>=0;i--)if(String(rows[i][0]).trim()===target)return rows[i][1];return null}
function saveRequest_(clientRequestId,orderId,requestId){const sheet=getSpreadsheet_().getSheetByName(SHEETS.REQUESTS);if(sheet)sheet.appendRow([clientRequestId,orderId,new Date(),hashShort_(clientRequestId+'|'+orderId+'|'+requestId)])}
function writeAudit_(requestId,actor,action,entityId,result,detail){try{const s=getSpreadsheet_().getSheetByName(SHEETS.AUDIT);if(s)s.appendRow([new Date(),safeCell_(requestId),safeCell_(actor),safeCell_(action),safeCell_(entityId),safeCell_(result),safeCell_(detail)])}catch(e){Logger.log('Audit log gagal: '+e)}}
function logError_(requestId,action,code,err){try{const s=getSpreadsheet_().getSheetByName(SHEETS.ERRORS);if(s)s.appendRow([new Date(),safeCell_(requestId),safeCell_(action),safeCell_(code),safeCell_(err&&err.message?err.message:String(err)),safeCell_(err&&err.stack?err.stack:'')])}catch(e){Logger.log('Error log gagal: '+e)}}
function writeSetting_(sheet,key,value,description){if(!sheet)return;const last=sheet.getLastRow();let row=0;if(last>=2){const keys=sheet.getRange(2,1,last-1,1).getDisplayValues().flat();for(let i=0;i<keys.length;i++)if(String(keys[i]).trim()===key){row=i+2;break}}if(!row)row=sheet.getLastRow()+1;sheet.getRange(row,1,1,4).setValues([[key,value,description,new Date()]])}
function enforcePublicTrackRateLimit_(id){enforceRateLimit_('public-track:'+hashShort_(normalizeOrderId_(id)||'invalid'),APP.PUBLIC_TRACK_LIMIT,APP.PUBLIC_TRACK_WINDOW)}
function enforceRateLimit_(key,limit,windowSeconds){if(!checkRate_(key,limit,windowSeconds))throw appError_('RATE_LIMITED','Terlalu banyak permintaan. Tunggu beberapa menit lalu coba lagi.')}
function checkRate_(key,limit,windowSeconds){const c=CacheService.getScriptCache(),k='rl:'+hashShort_(key),n=Number(c.get(k)||0);if(n>=limit)return false;c.put(k,String(n+1),windowSeconds);return true}
function requireAdmin_(token){const clean=String(token||'').trim();if(!clean||clean.length<20)throw appError_('ADMIN_REQUIRED','Sesi admin diperlukan.');if(!CacheService.getScriptCache().get('admin:'+clean))throw appError_('ADMIN_SESSION_EXPIRED','Sesi admin kedaluwarsa. Silakan login lagi.');return true}
function renderAdmin_(){try{return HtmlService.createTemplateFromFile('index').evaluate().setTitle('Tama Andrea Studio — Admin').addMetaTag('viewport','width=device-width, initial-scale=1').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}catch(e){return HtmlService.createHtmlOutput('<!doctype html><html lang="id"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="font-family:system-ui;padding:32px"><h1>Admin belum siap</h1><p>File index.html untuk panel admin belum tersedia.</p></body></html>')}}
function readPostBody_(e){const content=e&&e.postData&&e.postData.contents?String(e.postData.contents):'{}';if(content.length>APP.MAX_BODY_BYTES)throw appError_('PAYLOAD_TOO_LARGE','Ukuran permintaan melebihi batas.');try{return JSON.parse(content)}catch(_){if(e&&e.parameter)return e.parameter;throw appError_('INVALID_JSON','Data yang dikirim bukan JSON yang valid.')}}
function getParam_(e,key){return e&&e.parameter?String(e.parameter[key]||''):''}
function jsonResponse_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}
function errorResponse_(code,message,requestId){return jsonResponse_({status:'error',code:code,message:message,requestId:requestId})}
function errorObject_(code,message,requestId){return{status:'error',code:code,message:message,requestId:requestId}}
function publicErrorMessage_(err){return err&&err.code?String(err.message||'Permintaan tidak dapat diproses.'):'Server mengalami kendala. Silakan coba lagi.'}
function appError_(code,message){const e=new Error(message);e.code=code;return e}
function makeRequestId_(){return'REQ-'+Utilities.getUuid().replace(/-/g,'').slice(0,20).toUpperCase()}
function makeToken_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'')}
function hash_(value,salt){let text=String(salt)+'|'+String(value);for(let i=0;i<2500;i++)text=bytesToHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,text,Utilities.Charset.UTF_8));return text}
function hashShort_(text){return bytesToHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(text),Utilities.Charset.UTF_8)).slice(0,20)}
function bytesToHex_(bytes){return bytes.map(function(b){const n=b<0?b+256:b;return('0'+n.toString(16)).slice(-2)}).join('')}
function safeCell_(value){const text=sanitizePlain_(value,10000);return/^[=+\-@]/.test(text)?"'"+text:text}
function sanitizePlain_(value,max){const text=String(value==null?'':value).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim();return text.length>max?text.slice(0,max):text}
function normalize_(value){return normalizeSearch_(value)}
function normalizeSearch_(value){return String(value==null?'':value).toLowerCase().trim()}
function normalizeIdentity_(value){return normalizeSearch_(String(value||'').replace(/[^\p{L}\p{N} ]/gu,'').replace(/\s+/g,' '))}
function normalizeEmail_(value){return String(value||'').trim().toLowerCase()}
function normalizeOrderId_(value){const raw=sanitizePlain_(value,30).toUpperCase().replace(/^ORD[-\s]?/,'');if(!raw)return'';const id=APP.ORDER_PREFIX+raw.padStart(APP.ORDER_WIDTH,'0');return/^ORD-\d{1,12}$/.test(id)?id:''}
function normalizeClientRequestId_(value){const text=sanitizePlain_(value,100);if(!text)return'';if(!/^[A-Za-z0-9._:-]{8,100}$/.test(text))throw appError_('VALIDATION_ERROR','Client Request ID tidak valid.');return text}
function valueString_(value){return value==null?'':String(value)}
function parseNumber_(value){const n=Number(String(value==null?'':value).replace(/[^\d.-]/g,''));return isNaN(n)?0:n}
function formatRupiah_(value){return new Intl.NumberFormat('id-ID').format(parseNumber_(value))}
function roundToThousand_(value){return Math.max(0,Math.round(Number(value||0)/1000)*1000)}
function formatDate_(value){const d=value instanceof Date?value:new Date(value);return isNaN(d.getTime())?'':Utilities.formatDate(d,APP.TIMEZONE,'dd/MM/yyyy')}
function formatDateTime_(value){return Utilities.formatDate(value instanceof Date?value:new Date(value),APP.TIMEZONE,'dd/MM/yyyy HH:mm:ss')}
function formatDateTimeValue_(value){if(!value)return'';try{return formatDateTime_(value)}catch(_){return String(value)}}
function formatDateValue_(value){if(!value)return'';try{return formatDate_(value)}catch(_){return String(value)}}
function nowIso_(){return new Date().toISOString()}
function computeDaysLeft_(dateValue){if(!dateValue)return'';const due=dateValue instanceof Date?dateValue:new Date(dateValue);if(isNaN(due.getTime()))return'';const t=new Date(),a=new Date(t.getFullYear(),t.getMonth(),t.getDate()),b=new Date(due.getFullYear(),due.getMonth(),due.getDate());return Math.ceil((b-a)/86400000)}
function addBusinessDays_(date,days){const d=new Date(date.getTime());let left=Number(days)||0;while(left>0){d.setDate(d.getDate()+1);const day=d.getDay();if(day!==0&&day!==6)left--}return d}
function parseDateInput_(value,label){const text=sanitizePlain_(value,40);if(!text)throw appError_('VALIDATION_ERROR',label+' diperlukan.');const d=new Date(text);if(isNaN(d.getTime()))throw appError_('VALIDATION_ERROR',label+' tidak valid.');return d}
function validateEnum_(value,allowed,label){const text=sanitizePlain_(value,100);if(allowed.indexOf(text)===-1)throw appError_('VALIDATION_ERROR',label+' tidak valid.');return text}
function clampInt_(value,min,max,label){const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw appError_('VALIDATION_ERROR',label+' tidak valid.');return n}
function hasOwn_(obj,key){return Object.prototype.hasOwnProperty.call(obj,key)}
function validatePayloadSize_(p){if(JSON.stringify(p||{}).length>APP.MAX_BODY_BYTES)throw appError_('PAYLOAD_TOO_LARGE','Data yang dikirim terlalu besar.')}
function findCatalogKey_(item){const n=normalizeSearch_(item),keys=Object.keys(SERVICE_CATALOG);for(let i=0;i<keys.length;i++){const k=normalizeSearch_(keys[i]);if(n===k||n.indexOf(k)!==-1||k.indexOf(n)!==-1)return keys[i]}return null}
function splitServices_(value){return String(value||'').split(/,|\n|;/).map(function(v){return v.trim()}).filter(Boolean)}
function maskName_(name){const parts=String(name||'').trim().split(/\s+/).filter(Boolean);if(!parts.length)return'—';return parts.map(function(p){return p.length<=2?p.charAt(0)+'•':p.slice(0,2)+'•'.repeat(Math.min(4,Math.max(2,p.length-2)))}).join(' ')}
