/* Tama Andrea Studio — API compatibility, security and observability layer.
 * Loaded together with code.gs in the same Apps Script project.
 * No secrets are stored in source control.
 */
const API_STANDARD=Object.freeze({version:'2026.1',tokenTtlSeconds:900});
function makeRequestId_(){return 'req_'+Utilities.getUuid().replace(/-/g,'').slice(0,24)}
function makeToken_(){return Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'')}
function hashShort_(value){const bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(value||''),Utilities.Charset.UTF_8);return bytes.map(function(b){const n=(b+256)%256;return('0'+n.toString(16)).slice(-2)}).join('').slice(0,16)}
function appError_(code,message){const e=new Error(message||code);e.code=code;return e}
function publicErrorMessage_(err){const code=String(err&&err.code||'');const safe={VALIDATION_ERROR:'Data permintaan tidak valid.',NOT_FOUND:'Data tidak ditemukan.',RATE_LIMITED:'Terlalu banyak permintaan. Silakan coba lagi nanti.',PAYLOAD_TOO_LARGE:'Data yang dikirim terlalu besar.',UNKNOWN_ACTION:'Aksi tidak didukung.',CONFIG_ERROR:'Konfigurasi layanan belum benar.',SETUP_REQUIRED:'Backend belum selesai dikonfigurasi.',UNAUTHORIZED:'Akses ditolak.',FORBIDDEN:'Akses tidak diizinkan.'};return safe[code]||'Server tidak dapat memproses permintaan.'}
function jsonResponse_(payload){return ContentService.createTextOutput(JSON.stringify(payload||{})).setMimeType(ContentService.MimeType.JSON)}
function errorResponse_(code,message,requestId){return jsonResponse_({status:'error',error:{code:String(code||'INTERNAL_ERROR'),message:String(message||'Terjadi kesalahan.')},code:String(code||'INTERNAL_ERROR'),message:String(message||'Terjadi kesalahan.'),requestId:requestId||makeRequestId_(),apiVersion:API_STANDARD.version})}
function getParam_(e,key){return e&&e.parameter?String(e.parameter[key]||'').trim():''}
function readPostBody_(e){const raw=e&&e.postData&&e.postData.contents?String(e.postData.contents):'';if(!raw)throw appError_('VALIDATION_ERROR','Body permintaan kosong.');if(raw.length>APP.MAX_BODY_BYTES)throw appError_('PAYLOAD_TOO_LARGE','Data yang dikirim terlalu besar.');try{return JSON.parse(raw)}catch(_){throw appError_('VALIDATION_ERROR','Format JSON tidak valid.')}}
function getPublicStats_(){const s=getOrdersSheet_(),last=s.getLastRow(),out={totalPesanan:0,pending:0,proses:0,review:0,selesai:0,dibatalkan:0};if(last<2)return out;s.getRange(2,1,last-1,13).getValues().forEach(function(r){if(!r[0])return;out.totalPesanan++;const st=normalizeSearch_(r[12]);if(st==='pending')out.pending++;else if(st==='proses')out.proses++;else if(st==='review')out.review++;else if(st==='selesai')out.selesai++;else if(st==='dibatalkan')out.dibatalkan++});return out}
function maskName_(name){const parts=String(name||'').trim().split(/\s+/).filter(Boolean);return parts.map(function(p){return p.length<=2?p.charAt(0)+'*':p.charAt(0)+'*'.repeat(Math.min(3,p.length-1))}).join(' ')}
function publicOrder_(o){return{id:o.id,nama:maskName_(o.nama),layanan:o.layanan,status:o.status,tenggat:o.tenggat,prioritas:o.prioritas,hariTersisa:o.hariTersisa}}
function verifyOrder_(id,name,email,rid){const normalized=normalizeOrderId_(id);if(!normalized)throw appError_('VALIDATION_ERROR','ID pesanan tidak valid.');const o=findOrderById_(normalized);if(!o)throw appError_('NOT_FOUND','Pesanan tidak ditemukan.');const n=normalizeSearch_(name),em=normalizeEmail_(email);if(!n||normalizeSearch_(o.nama)!==n||!em||normalizeEmail_(o.email)!==em){writeAudit_(rid,'public','VERIFY_ORDER',normalized,'FAILED','Verifikasi identitas gagal.');throw appError_('UNAUTHORIZED','Nama dan email tidak cocok dengan pesanan.')}const token=makeToken_();CacheService.getScriptCache().put('verified:'+hashShort_(normalized+':'+token),JSON.stringify({id:normalized,email:em,issuedAt:Date.now()}),API_STANDARD.tokenTtlSeconds);writeAudit_(rid,'public','VERIFY_ORDER',normalized,'SUCCESS','Verifikasi identitas berhasil.');return{status:'success',requestId:rid,id:normalized,verificationToken:token,expiresIn:API_STANDARD.tokenTtlSeconds}}
function getVerifiedOrder_(id,token,rid){const normalized=normalizeOrderId_(id),t=String(token||'').trim();if(!normalized||t.length<20)throw appError_('UNAUTHORIZED','Token verifikasi tidak valid.');const cached=CacheService.getScriptCache().get('verified:'+hashShort_(normalized+':'+t));if(!cached)throw appError_('UNAUTHORIZED','Sesi verifikasi telah berakhir.');const o=findOrderById_(normalized);if(!o)throw appError_('NOT_FOUND','Pesanan tidak ditemukan.');return{status:'success',requestId:rid,order:{id:o.id,nama:o.nama,email:o.email,wa:o.wa,layanan:o.layanan,os:o.os,metode:o.metode,brief:o.brief,tenggat:o.tenggat,status:o.status,biaya:o.biaya,statusPembayaran:o.statusPembayaran,revisi:o.revisi,link:o.link,prioritas:o.prioritas,hariTersisa:o.hariTersisa}}}
function maskEmail_(email){const p=String(email||'').split('@');if(p.length!==2)return'';return(p[0].charAt(0)||'')+'***@'+p[1]}
function configureAdminSecurity(){const p=PropertiesService.getScriptProperties();return{status:'success',configured:!!p.getProperty('TA_ADMIN_GATE_HASH')&&!!p.getProperty('TA_ADMIN_CODE_HASH'),message:'Gunakan Script Properties untuk credential admin. Jangan simpan credential di repository.'}}
function requireAdmin_(token){const t=String(token||'').trim();if(!t)throw appError_('UNAUTHORIZED','Sesi admin tidak valid.');const cached=CacheService.getScriptCache().get('admin-session:'+hashShort_(t));if(!cached)throw appError_('UNAUTHORIZED','Sesi admin telah berakhir.');return JSON.parse(cached)}
function adminLogin_(gate,code,name,email,password){const p=PropertiesService.getScriptProperties();if(hashShort_(gate)!==String(p.getProperty('TA_ADMIN_GATE_HASH')||''))throw appError_('UNAUTHORIZED','Kode gerbang tidak valid.');if(hashShort_(code)!==String(p.getProperty('TA_ADMIN_CODE_HASH')||''))throw appError_('UNAUTHORIZED','Kode akses tidak valid.');const expectedEmail=String(p.getProperty('TA_ADMIN_EMAIL')||'').trim().toLowerCase(),expectedPasswordHash=String(p.getProperty('TA_ADMIN_PASSWORD_HASH')||'');if(expectedEmail&&normalizeEmail_(email)!==expectedEmail)throw appError_('UNAUTHORIZED','Identitas admin tidak cocok.');if(expectedPasswordHash&&hashShort_(password)!==expectedPasswordHash)throw appError_('UNAUTHORIZED','Password admin tidak valid.');const token=makeToken_();CacheService.getScriptCache().put('admin-session:'+hashShort_(token),JSON.stringify({name:sanitizePlain_(name,80),email:normalizeEmail_(email),issuedAt:Date.now()}),API_STANDARD.tokenTtlSeconds);return{status:'success',token:token,expiresIn:API_STANDARD.tokenTtlSeconds}}
function renderAdmin_(){return HtmlService.createHtmlOutputFromFile('index').setTitle('TA Admin Console').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function getApiContract_(){return{status:'ok',service:'tama-andrea-studio-backend',apiVersion:API_STANDARD.version,backendVersion:APP.VERSION,time:nowIso_(),endpoints:{GET:['ping','stats','track','admin'],POST:['newOrder','verifyOrder','getVerifiedOrder']},security:['request-id','rate-limit','idempotency','input-validation','masked-tracking','verified-access','formula-injection-protection','audit-log','error-log'],dataPolicy:{customerSheetPublic:false,trackingDefault:'masked'}}}
function adminGate(value){const p=PropertiesService.getScriptProperties(),expected=String(p.getProperty('TA_ADMIN_GATE_HASH')||'');if(!expected)throw appError_('CONFIG_ERROR','Admin belum dikonfigurasi.');if(hashShort_(value)!==expected)throw appError_('UNAUTHORIZED','Kode gerbang tidak valid.');const token=makeToken_();CacheService.getScriptCache().put('admin-stage1:'+hashShort_(token),'1',300);return{status:'success',stageToken:token}}
function adminCode(stageToken,value){if(CacheService.getScriptCache().get('admin-stage1:'+hashShort_(stageToken))!=='1')throw appError_('UNAUTHORIZED','Tahap gerbang telah berakhir.');const p=PropertiesService.getScriptProperties();if(hashShort_(value)!==String(p.getProperty('TA_ADMIN_CODE_HASH')||''))throw appError_('UNAUTHORIZED','Kode akses tidak valid.');const token=makeToken_();CacheService.getScriptCache().put('admin-stage2:'+hashShort_(token),'1',300);return{status:'success',verifyToken:token}}
function adminVerify(verifyToken,identity){if(CacheService.getScriptCache().get('admin-stage2:'+hashShort_(verifyToken))!=='1')throw appError_('UNAUTHORIZED','Tahap verifikasi telah berakhir.');const p=PropertiesService.getScriptProperties(),email=normalizeEmail_(identity&&identity.email),password=String(identity&&identity.password||'');const expectedEmail=String(p.getProperty('TA_ADMIN_EMAIL')||'').trim().toLowerCase(),expectedPasswordHash=String(p.getProperty('TA_ADMIN_PASSWORD_HASH')||'');if(expectedEmail&&email!==expectedEmail)throw appError_('UNAUTHORIZED','Email admin tidak cocok.');if(expectedPasswordHash&&hashShort_(password)!==expectedPasswordHash)throw appError_('UNAUTHORIZED','Password admin tidak valid.');const token=makeToken_();CacheService.getScriptCache().put('admin-session:'+hashShort_(token),JSON.stringify({name:sanitizePlain_(identity&&identity.name||'Admin',80),email:email,issuedAt:Date.now()}),API_STANDARD.tokenTtlSeconds);return{status:'success',token:token,expiresIn:API_STANDARD.tokenTtlSeconds,adminName:sanitizePlain_(identity&&identity.name||'Admin',80)}}
function adminLogoutSecure(token){const t=String(token||'').trim();if(t)CacheService.getScriptCache().remove('admin-session:'+hashShort_(t));return{status:'success'}}
function getCustomers(token,query){requireAdmin_(token);const s=getSpreadsheet_().getSheetByName(SHEETS.CUSTOMERS),q=normalizeSearch_(query),out=[];if(!s||s.getLastRow()<2)return{status:'success',customers:out};s.getRange(2,1,s.getLastRow()-1,CUSTOMER_HEADERS.length).getValues().forEach(function(r){if(!r[0])return;const hay=normalizeSearch_([r[3],r[4],r[5],r[0]].join(' '));if(q&&!hay.includes(q))return;out.push({id:r[0],nama:r[3],email:r[4],wa:r[5],jumlah:r[6],orderTerakhir:r[7],status:r[8],catatan:r[9]})});return{status:'success',customers:out.slice(0,APP.MAX_PAGE_SIZE)}}
function getServiceCatalog(token){requireAdmin_(token);return{status:'success',catalog:Object.keys(SERVICE_CATALOG).map(function(k){const c=SERVICE_CATALOG[k];return{key:k,name:k,category:c.group,min:c.min,base:c.base,max:c.max,fixed:c.min===c.max,active:true,description:'Layanan aktif pada katalog backend.'}})}}
function saveServiceCatalog(data,token){requireAdmin_(token);const d=data||{};if(!String(d.name||d.key||'').trim())throw appError_('VALIDATION_ERROR','Nama layanan diperlukan.');const s=getSpreadsheet_().getSheetByName(SHEETS.SETTINGS);if(s)writeSetting_(s,'CATALOG_OVERRIDE_'+hashShort_(d.key||d.name),JSON.stringify({name:sanitizePlain_(d.name,150),category:sanitizePlain_(d.category,40),min:Number(d.min)||0,base:Number(d.base)||0,max:Number(d.max)||0,fixed:!!d.fixed,active:d.active!==false,description:sanitizePlain_(d.description,500)}),'Override katalog yang dikelola admin.');writeAudit_(makeRequestId_(),'admin','SAVE_CATALOG',String(d.key||d.name),'SUCCESS','Override katalog disimpan.');return{status:'success',message:'Override katalog disimpan.'}}
function getServiceNotes(token,query,category){requireAdmin_(token);const s=getSpreadsheet_().getSheetByName(SHEETS.SERVICE_NOTES),q=normalizeSearch_(query),cat=normalizeSearch_(category),out=[];if(!s||s.getLastRow()<2)return{status:'success',notes:out};s.getRange(2,1,s.getLastRow()-1,7).getValues().forEach(function(r){if(!r[0])return;const hay=normalizeSearch_([r[1],r[2],r[3],r[4],r[5]].join(' '));if(q&&!hay.includes(q))return;if(cat&&!normalizeSearch_(r[1]).includes(cat))return;out.push({id:r[0],category:r[1],title:r[2],summary:r[3],steps:r[4],warnings:r[5]})});return{status:'success',notes:out.slice(0,APP.MAX_PAGE_SIZE)}}
function saveServiceNote(data,token){requireAdmin_(token);const d=data||{},s=getSpreadsheet_().getSheetByName(SHEETS.SERVICE_NOTES);if(!s)throw appError_('SETUP_REQUIRED','Sheet catatan belum tersedia.');const id=sanitizePlain_(d.id,80)||('NOTE-'+hashShort_(Date.now()+'|'+Math.random()));const last=s.getLastRow();let row=0;if(last>=2){const ids=s.getRange(2,1,last-1,1).getDisplayValues().flat();for(let i=0;i<ids.length;i++)if(String(ids[i])===id){row=i+2;break}}const values=[id,sanitizePlain_(d.category,80),sanitizePlain_(d.title,160),sanitizePlain_(d.summary,1000),sanitizePlain_(d.steps,5000),sanitizePlain_(d.warnings,1000),new Date()];if(row)s.getRange(row,1,1,7).setValues([values]);else s.appendRow(values);writeAudit_(makeRequestId_(),'admin','SAVE_NOTE',id,'SUCCESS','Catatan servis disimpan.');return{status:'success',id:id}}
function getBootKeys(token,query,type){requireAdmin_(token);const s=getSpreadsheet_().getSheetByName(SHEETS.BOOT_KEYS),q=normalizeSearch_(query),t=normalizeSearch_(type),out=[];if(!s||s.getLastRow()<2)return{status:'success',items:out};s.getRange(2,1,s.getLastRow()-1,7).getValues().forEach(function(r){if(!r[0])return;const hay=normalizeSearch_([r[0],r[1],r[2],r[3],r[4],r[5]].join(' '));if(q&&!hay.includes(q))return;if(t&&!normalizeSearch_(r[1]).includes(t))return;out.push({keyId:r[0],brand:r[0],type:r[1],model:r[2],bios:r[3],boot:r[4],notes:r[5]})});return{status:'success',items:out.slice(0,APP.MAX_PAGE_SIZE)}}
function saveBootKey(data,token){requireAdmin_(token);const d=data||{},s=getSpreadsheet_().getSheetByName(SHEETS.BOOT_KEYS);if(!s)throw appError_('SETUP_REQUIRED','Sheet Boot Menu belum tersedia.');const id=sanitizePlain_(d.keyId,80)||('BOOT-'+hashShort_(Date.now()+'|'+Math.random()));const values=[id,sanitizePlain_(d.type,40),sanitizePlain_(d.model,160),sanitizePlain_(d.bios,100),sanitizePlain_(d.boot,100),sanitizePlain_(d.notes,1500),new Date()];const last=s.getLastRow();let row=0;if(last>=2){const ids=s.getRange(2,1,last-1,1).getDisplayValues().flat();for(let i=0;i<ids.length;i++)if(String(ids[i])===id){row=i+2;break}}if(row)s.getRange(row,1,1,7).setValues([values]);else s.appendRow(values);writeAudit_(makeRequestId_(),'admin','SAVE_BOOT_KEY',id,'SUCCESS','Referensi Boot Menu disimpan.');return{status:'success',id:id}}
function adminExtendedHealthCheck(token){requireAdmin_(token);return runHealthCheck()}
function getAdminSettings(token){requireAdmin_(token);const s=getSpreadsheet_().getSheetByName(SHEETS.SETTINGS),out=[];if(!s||s.getLastRow()<2)return{status:'success',settings:out};s.getRange(2,1,s.getLastRow()-1,4).getValues().forEach(function(r){if(r[0])out.push({key:r[0],value:r[1],description:r[2]})});return{status:'success',settings:out.slice(-100)}}
function getAuditRecent(token,limit){requireAdmin_(token);const s=getSpreadsheet_().getSheetByName(SHEETS.AUDIT),out=[];if(!s||s.getLastRow()<2)return{status:'success',items:out};const n=Math.min(Number(limit)||35,100),last=s.getLastRow(),start=Math.max(2,last-n+1);s.getRange(start,1,last-start+1,7).getDisplayValues().reverse().forEach(function(r){out.push(r)});return{status:'success',items:out}}
function getErrorRecent(token,limit){requireAdmin_(token);const s=getSpreadsheet_().getSheetByName(SHEETS.ERRORS),out=[];if(!s||s.getLastRow()<2)return{status:'success',items:out};const n=Math.min(Number(limit)||35,100),last=s.getLastRow(),start=Math.max(2,last-n+1);s.getRange(start,1,last-start+1,6).getDisplayValues().reverse().forEach(function(r){out.push(r)});return{status:'success',items:out}}
